name = "4.Character & Attitude"
type = "word"
order = 1

words_1 = {
    "generous to a fault": "지나칠 정도로 관대한",
    "heart of gold": "마음씨가 아주 착한",
    "all heart": "매우 친절한, 동정심 많은",
    "give of oneself": "헌신하다, 자신을 바치다",
    "give the shirt off one’s back": "무엇이든 내줄 만큼 너그럽다",
    "kind-hearted": "친절한, 마음씨 고운",
    "caring person": "배려심 있는 사람",
    "to a fault": "지나칠 정도로",
    "gracious": "상냥한, 정중한",

    "hard as nails": "매우 냉혹한, 강인한",
    "heart of stone": "냉정한, 무자비한",
    "cold fish": "냉담한 사람",
    "the ice queen": "얼음 여왕, 차갑고 냉정한 여자",
    "callous": "냉담한, 무정한",
    "ruthless": "무자비한, 가차 없는",
    "unfeeling": "감정 없는, 무정한",
    "go up against": "~에 맞서다, 대항하다",
    "as ~ as the next person": "다른 사람만큼 ~하다",
    "go toe to toe with": "정면으로 맞서다",
    "grumpy": "심술궂은, 성미 까다로운",
    "deep down": "마음속 깊이",
    "no wonder": "당연하다, 놀랄 일 아니다",

    "rip off": "바가지를 씌우다, 사기치다",
    "pull a fast one on": "~을 속이다",
    "pull the wool over someone’s eyes": "~를 속이다, 눈을 가리다",
    "put one over on": "~를 속이다",
    "take for a ride": "~를 속이다, 속여 이용하다",
    "play for a fool": "~를 바보 취급하다, 속이다",
    "fleece": "바가지를 씌우다, 뜯어내다",
    "con": "사기, 속임수",
    "swindle": "사취하다, 속이다",
    "defraud": "속여 빼앗다",
    "bilk": "사취하다, 속이다",
    "swindler": "사기꾼",
    "rip-off artists": "사기꾼, 바가지 씌우는 사람",
    "trickster": "속이는 사람, 사기꾼",
    "scam": "사기",
    "rip-off": "바가지, 사기",
    "in mint condition": "완전 새것 같은 상태",
    "garage": "차고, 정비소",
    "knockoff": "짝퉁, 모조품",
    "authenticate": "진짜임을 입증하다",
    "go down the drain": "허비되다, 수포로 돌아가다",
    "dump": "버리다, 쓰레기장, 떠넘기다",
    "smell from a mile away": "누가 봐도 티가 나다, 금방 알 수 있다",

    "be one’s own woman(man)": "독립적인 사람이다",
    "strike on one’s own": "독립하다, 스스로 시작하다",
    "stand on one’s own two feet": "자립하다",
    "go it alone": "혼자서 해내다",
    "go one’s own way": "자기 길을 가다",
    "self-reliant": "자립적인",
    "self-sufficient": "자립적인, 자급자족하는",
    "set one’s own course": "자신의 길을 정하다",
    "have someone’s back": "~을 지지하다, 뒤를 봐주다",
    "hardly": "거의 ~않다",

    "lean on": "의지하다",
    "freeload off (of)": "~에 얹혀살다, 얻어먹다",
    "freeload on": "~에 얹혀살다, 얻어먹다",
    "leech off (of)": "~에 기생하다",
    "sponge off (of)": "~에 빌붙다, 얻어먹다",
    "live off (of)": "~에 의존해 살다",
    "mooch off (of)": "~에 얹혀살다",
    "moocher": "얹혀사는 사람, 빌붙는 사람",
    "awfully": "몹시, 매우",
    "leech": "거머리 / 기생하는 사람",
    "make a living": "생계를 꾸리다",
    "earn a living": "생계를 벌다",

    "people person": "사람들과 잘 어울리는 사람",
    "social butterfly": "사교성이 아주 좋은 사람",
    "like hanging out with people": "사람들과 어울리기를 좋아하다",
    "easy to be around (with)": "같이 있으면 편안한",
    "mix with": "~와 어울리다",
    "go the extra mile to": "더 노력하다, 특별히 애쓰다",
    "party person": "파티를 즐기는 사람",
    "the life of the party": "파티의 분위기 메이커",
    "come out of one’s shell": "내성에서 벗어나다",
    "break out of one’s shell": "내성에서 벗어나다",
    "go into one’s shell": "내성적으로 되다, 자기 안으로 숨다",

    "keep to oneself": "자기만의 시간을 가지다, 남과 어울리지 않다",
    "prefer one’s own company": "혼자 있기를 선호하다",
    "like being on one’s own": "혼자 있기를 좋아하다",
    "like being by one’s own": "혼자 있기를 좋아하다",
    "lone wolf": "외톨이, 혼자 행동하는 사람",
    "be a loner": "외톨이다",
    "social recluse": "사회적 은둔자",
    "social hermit": "사회와 단절한 은둔자",
    "mingle with": "~와 섞이다, 어울리다",
    "tune in to": "귀 기울이다, 맞추다",
    "leisure": "여가, 자유 시간",
    "wallflower": "소심해서 어울리지 못하는 사람",
    "stick in the mud": "재미없고 보수적인 사람",
    "square peg in a round hole": "주변과 맞지 않는 사람",
    "social misfit": "사회 부적응자",
    "social outcast": "사회적으로 소외된 사람",
}