name = "5.Emotions & Health"
type = "word"
order = 5

words_1 = {
    "as happy as a clam": "매우 행복한",
    "on cloud nine": "아주 행복한, 황홀한",
    "walk on air": "기뻐서 붕 뜬 듯하다",
    "in a good mood": "기분이 좋은",
    "in high spirits": "들뜬, 의기양양한",
    "on top of the world": "세상을 다 가진 듯한 기분",
    "over the moon": "너무 기뻐서 들뜬",
    "chipper": "쾌활한, 기분 좋은",
    "close a deal with": "거래를 성사시키다",
    "break": "행운, 기회",
    "in a foul mood": "기분이 몹시 나쁜",
    "in a rotten mood": "최악의 기분인",
    "take out on": "(화 등을) ~에게 화풀이하다",
    "get hitched": "결혼하다",
    "psyched (up) about": "~에 들뜬, 신난",
    "pumped up about": "~에 신나서 들뜬",

    "out of sorts": "몸이 좋지 않은, 기분이 언짢은",
    "in a (blue) funk": "우울한, 풀이 죽은",
    "down in the dumps": "우울한, 의기소침한",
    "down in the mouth": "풀이 죽은, 시무룩한",
    "hangdog look": "풀이 죽은 표정",
    "long face": "우울한 표정",
    "go-to": "필요하면 찾게 되는",
    "put it down to experience": "경험으로 여기고 넘기다",

    "bummed out": "속상한, 실망한",
    "let down": "실망시키다, 낙심",
    "(much) to my disappointment": "매우 실망스럽게도",
    "to my dismay": "당황스럽게도, 실망스럽게도",
    "to my surprise": "놀랍게도",
    "bummer": "실망스러운 일",
    "letdown": "실망",

    "throw a (hissy) fit": "불같이 화내다",
    "blow up": "버럭 화내다",
    "blow a gasket": "버럭 화내다",
    "hit the roof": "몹시 화내다",
    "go berserk": "미쳐 날뛰다",
    "go ballistic": "몹시 화내다",
    "flip out": "화내다, 흥분하다",
    "lose it": "자제력을 잃다",
    "go off the deep end": "이성을 잃고 화내다",
    "fly off the handle": "버럭 화내다",
    "snap": "화를 참지 못하다, 무너지다",
    "have a fit": "불같이 화내다",
    "hit the ceiling": "몹시 화내다",

    "driving nuts": "미치게 하다, 짜증 나게 하다",
    "drive up the wall": "짜증 나게 하다",
    "get on someone’s nerves": "신경을 건드리다",
    "get under someone's skin": "짜증 나게 하다",
    "rattle": "당황하게 하다, 짜증나게 하다",
    "stick up for": "~을 옹호하다, 두둔하다",
    "be getting to": "짜증나게 하다",
    "rub the wrong way": "신경 거슬리게 하다",

    "on edge": "신경이 곤두서 있는",
    "a bundle of nerves": "긴장한 상태",
    "sweat bullets": "몹시 초조해하다",
    "on pins and needles": "안절부절못하는",
    "jittery": "신경과민인, 안절부절못하는",
    "worried sick": "몹시 걱정하는",

    "scared to death (of)": "몹시 두려워하다",
    "scared out of one’s mind": "엄청나게 겁먹다",
    "shake like a leaf": "벌벌 떨다",
    "to death": "~해서 죽을 지경인",
    "laid back": "차분한, 느긋한",

    "green with envy (over)": "몹시 부러워하는",
    "eaten up with jealousy": "질투심에 사로잡힌",
    "sour grapes": "억지로 깎아내림, 못 가진 것에 대한 불평",
    "sick with envy": "질투로 속이 아픈",
    "twist around": "왜곡하다",
    "eaten up with rust": "녹슬어 망가진",
    "talk about": "~도 참 대단하네, (감탄/비꼼)",
}

words_2 = {
    # 원한/감정
    "hold a grudge": "원한을 품다",
    "hold against": "~을 탓하다, 원망하다",
    "have it in for": "~에게 앙심을 품다",
    "resent": "분개하다, 원망하다",
    "be miffed": "화나다, 약간 삐치다",
    "be peeved": "짜증나다",
    "sabotage": "방해하다, 파괴하다",
    "worked up": "흥분한, 화난",
    "be out to": "~하려고 작정하다",

    # 건강/좋은 상태
    "in good shape": "좋은 컨디션이다",
    "in top form": "최상의 컨디션이다",
    "fit as a fiddle": "매우 건강한",
    "right as rain": "아주 건강한, 완전히 정상인",
    "(all) bright-eyed and bushy-tailed": "활기찬, 생기 넘치는",
    "look fit": "건강해 보이다",
    "in good health": "건강한",
    "be well on one’s way to": "~을 향해 착실히 나아가다",
    "formidable": "만만치 않은, 위압적인",
    "in no time": "곧, 금세",

    # 아플 때/회복
    "under the weather": "몸이 안 좋은",
    "not feel (like) oneself": "평소 같지 않다, 몸 상태가 이상하다",
    "sick as a dog": "아주 아픈",
    "come down with a cold": "감기에 걸리다",
    "get (a) hold of": "~을 손에 넣다, ~와 연락이 닿다",
    "take ~ off": "~만큼 쉬다",
    "treat": "치료하다, 대접",

    # 피곤/탈진
    "wiped out": "기진맥진한",
    "worn out": "녹초가 된",
    "pooped (out)": "기운 빠진, 지친",
    "tuckered out": "몹시 지친",
    "dead on one’s feet": "몹시 피곤한",
    "burned out": "탈진한, 지쳐버린",
    "be drained": "완전히 기운이 빠진",
    "be beat": "지친",
    "bone tired": "몹시 피곤한",
    "call it a night": "오늘은 그만하고 자러 가다",
    "A wear B out": "A가 B를 지치게 하다",
    "have a blast": "매우 즐겁다",
    "catch up on": "밀린 것을 만회하다, 보충하다",
    "call it a day": "오늘은 그만하다",
    "ready to drop": "쓰러질 정도로 지친",
    "run down": "지친, 활력이 없는",

    # 위기/죽음에 가까운 상황
    "hang by a thread": "풍전등화다, 위태롭다",
    "hang in the balance": "불안정한 상태에 있다",
    "touch-and-go": "아슬아슬한",
    "fall apart": "무너지다",
    "hit rock bottom": "최악의 상황에 이르다",
    "pull through": "회복하다, (위기를) 극복하다",
    "slip away": "서서히 죽다, 사라지다",
    "not long for this world": "머지않아 죽을",
    "at death’s door": "죽음 직전에",
    "have one foot in the grave": "죽음 문턱에 있다",

    # 극복
    "out of the woods": "위기를 벗어난",
    "turn the corner": "고비를 넘기다, 호전되다",
    "out of critical condition": "위독한 상태를 벗어난",
    "it’s safe to say": "틀림없이 ~라고 말할 수 있다",

    # 회복/치유
    "on the mend": "회복 중인",
    "(well) on the road to recovery": "회복 중인",
    "recuperate": "회복하다, 요양하다",
    "be back on one’s feet": "회복하다, 다시 일어서다",
    "take a turn for the better": "호전되다",
    "long haul": "오랜 시간, 긴 과정",
}

words_3 = {
    "He felt as happy as a clam after hearing the good news.": "좋은 소식을 듣고 그는 매우 행복했다",
    "She was as happy as a clam relaxing on the beach.": "그녀는 해변에서 쉬면서 매우 행복했다",
    "She’s been on cloud nine since the wedding.": "그녀는 결혼 이후로 아주 행복하다",
    "He was on cloud nine after getting the job.": "그는 직장을 얻은 후 아주 행복했다",
    "After winning the game, he was walking on air.": "경기에서 이긴 후 그는 기뻐서 붕 떠 있었다",
    "She walked on air when she heard she passed the exam.": "시험에 합격했다는 소식을 듣고 그녀는 기뻐서 붕 떠 있었다",
    "He’s in a good mood today because it’s sunny.": "오늘 그는 날씨가 맑아서 기분이 좋다",
    "She seemed in a good mood after lunch.": "점심을 먹고 그녀는 기분이 좋아 보였다",
    "The students were in high spirits before the trip.": "학생들은 여행 전에 들떠 있었다",
    "She was in high spirits at the party.": "그녀는 파티에서 의기양양했다",
    "He felt on top of the world after his success.": "성공 후 그는 세상을 다 가진 듯 기뻤다",
    "She’s on top of the world with her new promotion.": "그녀는 새 승진으로 세상을 다 가진 듯 기쁘다",
    "He was over the moon about the baby’s birth.": "그는 아기의 탄생에 너무 기뻤다",
    "She was over the moon after winning the lottery.": "복권에 당첨된 후 그녀는 너무 기뻤다",
    "She looked chipper despite the long day.": "긴 하루에도 불구하고 그녀는 쾌활해 보였다",
    "He’s always chipper in the mornings.": "그는 아침마다 항상 쾌활하다",

    "She was out of sorts after the long flight.": "그녀는 긴 비행 후 몸이 좋지 않았다",
    "He seemed out of sorts this morning.": "그는 오늘 아침 기분이 언짢아 보였다",
    "He’s been in a blue funk all week.": "그는 한 주 내내 우울했다",
    "She fell into a blue funk after failing the exam.": "시험에 떨어진 후 그녀는 우울해졌다",
    "She’s been down in the dumps since the breakup.": "그녀는 이별 후 우울했다",
    "He felt down in the dumps after losing his job.": "그는 직장을 잃고 의기소침했다",
    "He looked down in the mouth after the meeting.": "회의 후 그는 풀이 죽어 있었다",
    "She was down in the mouth because of the bad news.": "그녀는 나쁜 소식 때문에 시무룩했다",
    "He had a hangdog look after being scolded.": "그는 꾸중을 듣고 풀이 죽은 표정을 지었다",
    "She wore a hangdog look all day.": "그녀는 하루 종일 풀이 죽은 표정이었다",
    "He came in with a long face.": "그는 우울한 표정으로 들어왔다",
    "She had a long face after the argument.": "그녀는 말다툼 후 우울한 표정을 지었다",
    "She’s my go-to person for advice.": "그녀는 내가 조언이 필요할 때 찾는 사람이다",
    "This café is my go-to spot for studying.": "이 카페는 내가 공부할 때 찾는 단골 장소다",
    "He decided to put the mistake down to experience.": "그는 그 실수를 경험으로 여기고 넘겼다",
    "She put the failure down to experience and moved on.": "그녀는 실패를 경험으로 여기고 넘어갔다",

    "He was bummed out about the canceled concert.": "그는 콘서트가 취소돼 속상했다",
    "She felt bummed out after the bad grade.": "그녀는 나쁜 성적에 실망했다",
    "He felt really let down by his friends.": "그는 친구들에게 정말 실망했다",
    "The ending of the movie was such a letdown.": "그 영화의 결말은 정말 실망이었다",
    "Much to my disappointment, the trip was canceled.": "매우 실망스럽게도, 여행이 취소됐다",
    "Much to her disappointment, she didn’t get the job.": "매우 실망스럽게도 그녀는 일을 얻지 못했다",
    "To my dismay, the plan didn’t work.": "당황스럽게도 계획이 실패했다",
    "To her dismay, he refused to help.": "그녀가 당황스럽게도 그는 도움을 거절했다",
    "To my surprise, she agreed immediately.": "놀랍게도 그녀는 바로 동의했다",
    "To his surprise, the exam was easy.": "놀랍게도 시험은 쉬웠다",
    "That’s a real bummer.": "정말 실망스러운 일이다",
    "Missing the bus was a bummer.": "버스를 놓친 건 정말 실망이었다",
    "The concert was a letdown.": "그 콘서트는 실망이었다",
    "He felt a letdown after the excitement ended.": "그는 흥분이 가라앉자 실망을 느꼈다",
}
words_4 = {
    "She threw a hissy fit when she lost the game.": "그녀는 게임에서 지자 불같이 화를 냈다",
    "The child threw a fit in the store.": "그 아이는 가게에서 불같이 화를 냈다",
    "He blew up at his coworker.": "그는 동료에게 버럭 화를 냈다",
    "She blew up when she heard the news.": "그녀는 그 소식을 듣고 버럭 화를 냈다",
    "He blew a gasket after the mistake.": "그는 실수 후 버럭 화를 냈다",
    "She nearly blew a gasket when she saw the mess.": "그녀는 엉망인 걸 보고 거의 버럭 화를 냈다",
    "Dad hit the roof when I broke the window.": "내가 창문을 깨자 아버지가 몹시 화내셨다",
    "She hit the roof after hearing the rumor.": "그녀는 소문을 듣고 몹시 화를 냈다",
    "He went berserk when his car was stolen.": "그는 차가 도난당했을 때 미쳐 날뛰었다",
    "The fans went berserk after the victory.": "팬들은 승리 후 미쳐 날뛰었다",
    "She went ballistic when she found out the truth.": "그녀는 진실을 알자 몹시 화를 냈다",
    "He went ballistic over the mistake.": "그는 그 실수 때문에 몹시 화를 냈다",
    "He flipped out when the waiter spilled soup.": "웨이터가 수프를 쏟자 그는 화를 냈다",
    "She flipped out over the bad service.": "그녀는 나쁜 서비스에 화를 냈다",
    "He completely lost it during the meeting.": "그는 회의 중에 자제력을 잃었다",
    "She lost it when her phone broke.": "그녀는 휴대폰이 고장 나자 자제력을 잃었다",
    "He went off the deep end after the argument.": "그는 말다툼 후 이성을 잃고 화냈다",
    "She went off the deep end when she was betrayed.": "그녀는 배신당하자 이성을 잃고 화냈다",
    "He flew off the handle over a small issue.": "그는 작은 문제에도 버럭 화냈다",
    "She flew off the handle when she was interrupted.": "그녀는 방해받자 버럭 화냈다",
    "He snapped at his friend.": "그는 친구에게 화를 참지 못했다",
    "She finally snapped under pressure.": "그녀는 압박 속에서 결국 무너졌다",
    "The teacher had a fit over the noise.": "선생님은 소음 때문에 불같이 화를 냈다",
    "She had a fit when her plan was canceled.": "그녀는 계획이 취소되자 불같이 화냈다",
    "Dad hit the ceiling when he saw the bill.": "아버지는 청구서를 보시고 몹시 화내셨다",
    "She hit the ceiling after the mistake.": "그녀는 그 실수 후 몹시 화를 냈다",

    "This noise is driving me nuts.": "이 소음이 나를 미치게 한다",
    "Her constant questions drove him nuts.": "그녀의 끊임없는 질문이 그를 미치게 했다",
    "The delay is driving me up the wall.": "지연 때문에 나 정말 짜증난다",
    "His arrogance drives me up the wall.": "그의 거만함이 나를 짜증나게 한다",
    "Her attitude gets on my nerves.": "그녀의 태도가 내 신경을 건드린다",
    "Loud chewing really gets on my nerves.": "시끄럽게 씹는 건 정말 내 신경을 거슬린다",
    "His sarcasm gets under my skin.": "그의 빈정거림이 나를 짜증나게 한다",
    "She really got under my skin with her comments.": "그녀의 말이 정말 나를 짜증나게 했다",
    "The unexpected question rattled him.": "예상치 못한 질문이 그를 당황하게 했다",
    "Her rude remark rattled everyone.": "그녀의 무례한 말이 모두를 당황하게 했다",
    "She stuck up for her friend in the argument.": "그녀는 말다툼에서 친구를 두둔했다",
    "He always sticks up for his teammates.": "그는 늘 팀원들을 옹호한다",
    "The noise is really getting to me.": "그 소음이 나를 정말 짜증나게 한다",
    "Her complaints are starting to get to him.": "그녀의 불평이 그를 짜증나게 하고 있다",
    "His arrogance really rubs me the wrong way.": "그의 거만함이 정말 내 신경을 거슬린다",
    "The way she talks rubs people the wrong way.": "그녀의 말투가 사람들 신경을 거슬리게 한다",

    "She’s been on edge all day.": "그녀는 하루 종일 신경이 곤두서 있었다",
    "He gets on edge before exams.": "그는 시험 전에 신경이 곤두선다",
    "He’s a bundle of nerves before the interview.": "그는 면접 전에 긴장으로 가득하다",
    "She turned into a bundle of nerves on stage.": "그녀는 무대에서 긴장 덩어리가 되었다",
    "He was sweating bullets before the presentation.": "그는 발표 전에 몹시 초조해했다",
    "She sweated bullets waiting for the results.": "그녀는 결과를 기다리며 몹시 초조해했다",
    "I was on pins and needles waiting for the call.": "나는 전화를 기다리며 안절부절못했다",
    "They were on pins and needles during the exam.": "그들은 시험 동안 안절부절못했다",
    "She felt jittery before the speech.": "그녀는 연설 전에 안절부절못했다",
    "Caffeine makes me jittery.": "카페인은 나를 신경과민하게 만든다",
    "She was worried sick about her son.": "그녀는 아들 때문에 몹시 걱정했다",
    "I’m worried sick that he hasn’t called yet.": "그가 아직 전화를 안 해서 나는 몹시 걱정된다",

    "I was scared to death of the dark as a child.": "나는 어릴 때 어둠이 무서워 죽을 지경이었다",
    "She’s scared to death of spiders.": "그녀는 거미가 너무 무섭다",
    "He was scared out of his mind during the storm.": "그는 폭풍우 동안 엄청나게 겁먹었다",
    "They were scared out of their minds when the plane shook.": "비행기가 흔들릴 때 그들은 엄청나게 겁먹었다",
    "He was shaking like a leaf before the speech.": "그는 연설 전에 벌벌 떨었다",
    "She shook like a leaf when she saw the accident.": "그녀는 사고를 보고 벌벌 떨었다",
    "I was bored to death during the lecture.": "나는 강의 중에 지루해 죽을 지경이었다",
    "She worried to death about the test.": "그녀는 시험 때문에 죽을 정도로 걱정했다",
    "He’s so laid back about everything.": "그는 모든 일에 차분하다",
    "She stayed laid back even under pressure.": "그녀는 압박 속에서도 느긋하게 있었다",

    "She was green with envy over her friend’s success.": "그녀는 친구의 성공을 몹시 부러워했다",
    "He turned green with envy when he saw their new car.": "그는 그들의 새 차를 보고 몹시 부러워했다",
    "She was eaten up with jealousy after the breakup.": "그녀는 이별 후 질투심에 사로잡혔다",
    "He was eaten up with jealousy when he saw them together.": "그는 그들이 함께 있는 걸 보고 질투심에 사로잡혔다",
    "Calling the award worthless was just sour grapes.": "상을 무가치하다고 한 건 억지로 깎아내린 것이다",
    "His remark about the rich was pure sour grapes.": "부자들에 대한 그의 발언은 그저 못 가진 것에 대한 불평이었다",
    "She was sick with envy when she saw the jewelry.": "그녀는 그 보석을 보고 질투로 속이 아팠다",
    "He felt sick with envy at his colleague’s promotion.": "그는 동료의 승진에 질투로 속이 아팠다",
    "The politician twisted his words around.": "그 정치인은 그의 말을 왜곡했다",
    "She twisted the story around to make herself look good.": "그녀는 이야기를 왜곡해서 자신을 좋게 보이게 했다",
    "The old bike was eaten up with rust.": "그 오래된 자전거는 녹슬어 망가졌다",
    "The gate was completely eaten up with rust.": "그 대문은 완전히 녹슬어 망가졌다",
    "Talk about expensive!": "정말 비싸네!",
    "Talk about bad timing!": "정말 타이밍이 안 좋네!",
}

words_5 = {
    # 원한/감정
    "She still holds a grudge against him after all these years.": "그녀는 여전히 그에게 원한을 품고 있다",
    "It’s not healthy to hold a grudge for so long.": "그렇게 오래 원한을 품는 건 건강하지 않다",
    "I won’t hold your mistake against you.": "네 실수를 원망하지 않을게",
    "She held it against him that he forgot her birthday.": "그는 그녀의 생일을 잊은 걸 원망당했다",
    "The teacher seems to have it in for me.": "선생님이 나한테 앙심을 품은 것 같다",
    "He has it in for his boss after being treated unfairly.": "그는 부당한 대우 이후 상사에게 앙심을 품고 있다",
    "She resented being treated like a child.": "그녀는 아이 취급받는 것을 분개했다",
    "He resents his brother’s success.": "그는 형의 성공을 원망한다",
    "She was miffed when they didn’t invite her.": "그녀는 초대받지 못해 화가 났다",
    "He seemed miffed about the joke.": "그는 농담에 약간 삐친 것 같았다",
    "I was peeved at his rude comments.": "나는 그의 무례한 말에 짜증이 났다",
    "She gets peeved when people interrupt her.": "그녀는 사람들이 방해하면 짜증을 낸다",
    "Someone tried to sabotage the project.": "누군가 프로젝트를 방해하려 했다",
    "The enemy sabotaged the bridge.": "적이 다리를 파괴했다",
    "He was really worked up about the game.": "그는 경기 때문에 정말 흥분했다",
    "Don’t get so worked up over small things.": "작은 일에 그렇게 흥분하지 마라",
    "He’s out to prove himself.": "그는 자기 능력을 증명하려고 작정했다",
    "They’re out to win the championship.": "그들은 챔피언십을 따내려고 작정했다",

    # 건강/좋은 상태
    "She’s in good shape after months of training.": "몇 달간 훈련 후 그녀는 좋은 컨디션이다",
    "The car is still in good shape.": "그 차는 여전히 상태가 좋다",
    "The athlete is in top form for the race.": "그 선수는 경기를 위해 최상의 컨디션이다",
    "He was in top form during the concert.": "그는 콘서트에서 최고의 상태였다",
    "My grandmother is fit as a fiddle at 80.": "내 할머니는 80세에도 매우 건강하시다",
    "He feels fit as a fiddle after his vacation.": "그는 휴가 후 아주 건강하다고 느낀다",
    "After a nap, she felt right as rain.": "낮잠 후 그녀는 완전히 괜찮아졌다",
    "Don’t worry, you’ll be right as rain in a few days.": "걱정 마, 며칠 안에 완전히 괜찮아질 거야",
    "The students came to class bright-eyed and bushy-tailed.": "학생들은 활기차게 수업에 왔다",
    "She’s always bright-eyed and bushy-tailed in the mornings.": "그녀는 아침마다 늘 생기가 넘친다",
    "You look fit these days.": "너 요즘 건강해 보인다",
    "He looks fit for his age.": "그는 나이에 비해 건강해 보인다",
    "She’s in good health for her age.": "그녀는 나이에 비해 건강하다",
    "The doctor said he’s in good health.": "의사는 그가 건강하다고 말했다",
    "She is well on her way to becoming a doctor.": "그녀는 의사가 되는 길에 착실히 나아가고 있다",
    "He’s well on his way to recovery.": "그는 회복하는 길에 있다",
    "The team faces a formidable opponent.": "그 팀은 만만치 않은 상대와 맞선다",
    "She has a formidable reputation as a lawyer.": "그녀는 변호사로서 위압적인 명성을 가지고 있다",
    "We’ll be home in no time.": "금세 집에 도착할 거야",
    "She finished her homework in no time.": "그녀는 숙제를 금세 끝냈다",

    # 아플 때/회복
    "She’s feeling under the weather today.": "그녀는 오늘 몸이 안 좋다",
    "I was under the weather after the trip.": "여행 후 나는 몸이 안 좋았다",
    "I don’t feel like myself lately.": "요즘 몸 상태가 평소 같지 않다",
    "She said she didn’t feel herself this morning.": "그녀는 오늘 아침 몸이 이상하다고 말했다",
    "He was sick as a dog with the flu.": "그는 독감으로 아주 아팠다",
    "I felt sick as a dog after the meal.": "그 식사 후 나는 아주 아팠다",
    "She came down with a cold last night.": "그녀는 어젯밤 감기에 걸렸다",
    "I think I’m coming down with something.": "나 뭔가에 걸린 것 같아",
    "I finally got hold of my lawyer.": "드디어 변호사와 연락이 닿았다",
    "Can you get hold of some tickets?": "표 좀 구할 수 있어?",
    "He decided to take a week off.": "그는 일주일을 쉬기로 했다",
    "She took two days off from work.": "그녀는 이틀 휴가를 냈다",
    "The doctor treated her wound.": "의사는 그녀의 상처를 치료했다",
    "He treated us to dinner.": "그는 우리에게 저녁을 대접했다",
}
words_6 = {
    # 피곤/탈진
    "I was completely wiped out after the exam.": "시험 후 나는 완전히 지쳐버렸다",
    "She looked wiped out after the long day.": "그녀는 긴 하루 후 완전히 지쳐 보였다",
    "He was worn out from working late.": "그는 야근 때문에 녹초가 되었다",
    "My shoes are worn out.": "내 신발이 다 닳았다",
    "I’m pooped after running.": "달리기 후 나는 지쳤다",
    "She felt pooped out from the heat.": "그녀는 더위 때문에 지쳤다",
    "The kids were tuckered out after playing.": "아이들은 놀다가 지쳐버렸다",
    "I’m tuckered out from cleaning the house.": "집 청소하느라 완전히 지쳤다",
    "He was dead on his feet after the march.": "그는 행진 후 몹시 피곤했다",
    "I felt dead on my feet after work.": "나는 일 끝나고 몹시 피곤했다",
    "She felt burned out from stress.": "그녀는 스트레스로 완전히 지쳤다",
    "He got burned out after years of overwork.": "그는 과로로 지쳐버렸다",
    "I’m drained after that meeting.": "그 회의 후 나는 기운이 다 빠졌다",
    "She felt emotionally drained.": "그녀는 감정적으로 완전히 지쳤다",
    "I’m beat, let’s go home.": "나 지쳤어, 집에 가자",
    "He was beat after the long trip.": "그는 긴 여행 후 지쳤다",
    "I’m bone tired from moving.": "이사 때문에 몹시 피곤하다",
    "She was bone tired after the exam.": "그녀는 시험 후 몹시 피곤했다",
    "Let’s call it a night and rest.": "오늘은 이쯤 하고 쉬자",
    "They called it a night after the party.": "그들은 파티 후 그만하고 집에 갔다",
    "This work wore me out.": "이 일이 나를 지치게 했다",
    "Chasing the kids wore her out.": "아이들을 쫓아다니느라 그녀는 지쳤다",
    "We had a blast at the concert.": "우리는 콘서트에서 정말 즐거웠다",
    "They had a blast on vacation.": "그들은 휴가 동안 매우 즐거웠다",
    "I need to catch up on my sleep.": "나는 밀린 잠을 보충해야 한다",
    "He caught up on emails at work.": "그는 회사에서 밀린 이메일을 처리했다",
    "Let’s call it a day and go home.": "오늘은 이쯤 하고 집에 가자",
    "They called it a day after finishing the job.": "그들은 일을 끝내고 그만했다",
    "I’m ready to drop after running.": "달리기 후 나는 쓰러질 정도로 지쳤다",
    "She was ready to drop after shopping.": "그녀는 쇼핑 후 쓰러질 정도로 지쳤다",
    "He’s run down from overwork.": "그는 과로로 지쳐 있다",
    "She felt run down after exams.": "그녀는 시험 후 지쳐 있었다",

    # 위기/죽음에 가까운 상황
    "The patient’s life was hanging by a thread.": "환자의 생명이 위태로웠다",
    "His career is hanging by a thread.": "그의 경력은 위태롭다",
    "The result still hangs in the balance.": "결과가 아직 불안정하다",
    "His future hangs in the balance.": "그의 미래가 불안정하다",
    "It was touch-and-go whether he would survive.": "그가 살아남을지는 아슬아슬했다",
    "Her recovery was touch-and-go at first.": "그녀의 회복은 처음에는 아슬아슬했다",
    "She fell apart after the divorce.": "그녀는 이혼 후 무너졌다",
    "The plan fell apart in the end.": "그 계획은 결국 무너졌다",
    "He hit rock bottom after losing his job.": "그는 직장을 잃고 최악의 상황에 이르렀다",
    "Her health hit rock bottom last year.": "그녀의 건강은 작년에 최악이었다",
    "He pulled through after surgery.": "그는 수술 후 회복했다",
    "They pulled through the crisis together.": "그들은 함께 위기를 극복했다",
    "She slipped away peacefully at night.": "그녀는 밤에 평화롭게 세상을 떠났다",
    "Time slipped away quickly.": "시간이 빠르게 흘러갔다",
    "He’s not long for this world.": "그는 머지않아 죽을 것이다",
    "She looked like she was not long for this world.": "그녀는 오래 살 것 같지 않아 보였다",
    "He was at death’s door after the accident.": "그는 사고 후 죽음 직전이었다",
    "She felt at death’s door with the flu.": "그녀는 독감으로 죽을 지경이었다",
    "He has one foot in the grave.": "그는 죽음 문턱에 있다",
    "People said the old man had one foot in the grave.": "사람들은 그 노인이 죽음 문턱에 있다고 말했다",

    # 극복/회복
    "He’s finally out of the woods after surgery.": "그는 수술 후 마침내 위기를 벗어났다",
    "The company is out of the woods financially.": "그 회사는 재정적으로 위기를 벗어났다",
    "She turned the corner and started recovering.": "그녀는 고비를 넘기고 회복하기 시작했다",
    "The economy turned the corner last year.": "경제가 작년에 호전되었다",
    "He’s out of critical condition now.": "그는 이제 위독한 상태를 벗어났다",
    "The patient is out of critical condition.": "그 환자는 위독 상태를 벗어났다",
    "It’s safe to say the team will win.": "그 팀이 이길 거라고 확실히 말할 수 있다",
    "It’s safe to say she’s the best in class.": "그녀가 반에서 최고라고 확실히 말할 수 있다",

    # 회복/치유
    "She’s on the mend after her illness.": "그녀는 병 후에 회복 중이다",
    "The country is on the mend after the crisis.": "그 나라는 위기 후 회복 중이다",
    "He’s on the road to recovery.": "그는 회복 중이다",
    "She’s well on the road to recovery.": "그녀는 잘 회복되고 있다",
    "He needs time to recuperate.": "그는 회복할 시간이 필요하다",
    "She went to the countryside to recuperate.": "그녀는 회복하려고 시골로 갔다",
    "He’s back on his feet after the surgery.": "그는 수술 후 다시 일어섰다",
    "The business is back on its feet.": "그 사업은 다시 일어서고 있다",
    "She took a turn for the better after treatment.": "그녀는 치료 후 호전되었다",
    "His health took a turn for the better.": "그의 건강이 호전되었다",
    "Recovery will be a long haul.": "회복은 오랜 시간이 걸릴 것이다",
    "Building the company again will be a long haul.": "회사를 다시 세우는 건 긴 과정이 될 것이다",
}