name = "Season 1"
type = "TV show"
order = 1

words_1 = {
    "aegean": "에게 해의, 에게 해",
    "phylum": "문(동물분류)",
    "Haiti": "아이티(국가)",
    "hostess": "여자 주인, 접대원",
    "yearn": "갈망하다",
    "pin one’s hopes on": "~에 희망을 걸다",
    "trip": "발을 헛디디다, 발을 헛디딤",
    "boarding school": "기숙학교",
    "transvestite": "이성복장자",
    "doodle": "낙서하다, 끄적거리다",
    "spoof": "패러디, 풍자",
    "perspiration": "땀, 발한",
    "parallax": "시차(천문학)",
    "resent": "분개하다, 화내다",
    "sagittarius": "사수자리",
    "arbitrary": "임의의, 제멋대로의",
    "constellation": "별자리",
    "guts": "용기, 배짱",
    "carnal": "육체의, 육욕의",
    "hinder": "방해하다",
    "sentiment": "정서, 감정",
    "aforementioned": "앞서 언급한",
    "query": "질문, 문의",
    "in contradistinction to something": "~와 대조적으로",
    "hit on": "불현듯 떠올리다, 작업을 걸다",
    "defect": "결함, 탈퇴하다",
    "dispute": "분쟁, 논쟁하다",
    "custody": "양육권, 구류",
    "have a scene": "소동을 벌이다",
    "ergo": "그러므로, 따라서",
    "hitch": "문제, 장애",
    "aftermath": "여파, 결과",
    "pantsing": "바지 벗기기 장난",
    "kick back": "편히 쉬다, 리베이트",
    "ale": "에일 맥주",
    "send one’s regards": "안부를 전하다",
    "redundant": "여분의, 불필요한",
    "spell out": "분명히 설명하다",
    "veritable": "진정한, 참된",
    "renege": "약속을 어기다",
    "proffer": "제의하다, 제공하다",
}

words_2 = {
    "pad thai": "팟타이(태국 볶음국수)",
    "latter": "후자의, 뒤쪽의",
    "puffy": "부푼, 부은",
    "swoosh": "쉭 하는 소리, 나이키 로고",
    "rife": "만연한, 가득한",
    "swoop": "급습하다, 덮치다",
    "predicate": "단정하다, ~의 근거를 두다",
    "feat": "위업, 업적",
    "dolly": "이동식 받침대, 인형",
    "fulcrum": "지렛점",
    "thou": "그대(고어)",
    "congress": "회의, 국회",
    "sexual congress": "성교",
    "in any case": "어쨌든",
    "flatware": "식기류",
    "immaculate": "흠 없는, 깨끗한",
    "as to": "~에 관하여",
    "jury": "배심원단",
    "register": "음역",
    "rouse": "깨우다, 자극하다",
    "premise": "전제",
    "premises": "부동산 건물",
    "granted": "~이긴 하지만, 승인된",
    "folk cure": "민간 요법",
    "unorthodox": "비정통의, 특이한",
    "perse": "그 자체로, 고유하게",
    "at length": "상세히, 길게",
    "otolaryngology": "이비인후과학",
    "proctology": "항문학",
    "for lack of better word": "뭐라 말해야 할지 모르겠지만",
    "you are all over the place": "정신이 산만하다",
    "color": "왜곡하다",
    "you are a doll": "넌 참 좋은 사람이야",
    "homie": "친구(속어)",
    "grap a napkin": "냅킨을 집다",
    "got served": "공격당하다, 망신당하다",
    "so too": "또한 마찬가지로",
    "dowel": "접합용 핀",
    "media center": "TV 수납장",
    "corrugated": "물결 모양의, 골이 진",
    "sluice": "수문, 물길, 세차게 흐르다",
    "ground": "접지하다",
    "junkyard": "고철 더미, 폐차장",
    "scrap aluminum": "고철 알루미늄",
}
words_3 = {
    "horde": "큰 무리, 군중",
    "wield": "휘두르다, 행사하다",
    "slash": "긋다, 대폭 줄이다",
    "prehensile": "잡기에 적합한, 물건을 잡을 수 있는",
    "swat": "찰싹 때리다, 찰싹 때림",
    "mead": "벌꿀 술",
    "flank": "측면, 옆구리",
    "peasant": "농민, 무식쟁이",
    "rogue": "악당, 불량배, 사기꾼",
    "civil servant": "공무원",
    "propensity": "성향, 경향",
    "penny for your thoughts": "무슨 생각해?",
    "chaste": "순결한, 정숙한",
    "infatuation": "열병 같은 사랑, 심취",
    "devolve": "(권리) 양도하다, (의무) 지우다, (재산) 이전되다",
    "smoulder": "(불꽃이 서서히) 타다, (불만이) 들끓다",
    "wreckage": "잔해, 파편",
    "relentless": "가차 없는, 끈질긴",
    "dietician": "영양사",
    "limp": "기운 없는, 절뚝거리다",
    "lazy eye": "약시, 사시",
    "pitfall": "함정, 위험",
    "harassment": "괴롭힘, 희롱",
    "harass": "괴롭히다, 희롱하다",
    "quibble": "옥신각신하다, 트집 잡다",
    "stipulate": "규정하다, 명기하다",
    "parameter": "한도, 매개변수, 기준",
    "extraneous": "관련 없는, 외부의",
    "spittle": "침, 타액",
    "inaction": "무행동, 게으름",
    "mope": "침울해하다",
    "tedious": "지루한",
    "eligible": "자격 있는, (신랑,신부로서)자격이 있는",
    "you’re in for a treat": "좋은 걸 보게 될 거야",
    "compile": "편집하다, 수집하다",
    "take into account": "고려하다",
    "feline": "고양잇과의, 고양이 같은",
    "geneticist": "유전학자",
    "be torn between": "~ 사이에서 갈등하다",
    "sergeant": "하사관",
    "cuddly": "껴안고 싶은, 귀여운",
    "chisel": "끌, 조각하다",
    "perspire": "땀을 흘리다",
    "dissipate": "흩뜨리다, 소멸하다",
    "stuff oneself": "실컷 먹다, 과식하다",
    "stuffed": "배부른, 가득 찬",
    "kick off": "시작하다",
    "lean in": "몸을 기울이다, 적극 참여하다",
    "tentative": "잠정적인, 머뭇거리는",
    "sparsely": "드문드문, 희박하게",
    "venereal": "성병의",
    "bounce back": "회복하다, 되돌아오다",
    "nip": "꼬집다, 물다",
    "in the bud": "싹을 (초기에) ~하다",
    "pick up": "회복되다, 개선되다",
    "chafe": "비비다, 쓸리다, 짜증내다",
    "centripetal": "구심력의",
    "intertial": "관성의",
    "concussion": "뇌진탕",
}
words_4 = {
    "road block": "도로 봉쇄, 장애물",
    "put it on the back burner": "우선순위에서 뒤로 미루다",
    "in order": "정상 작동하는, 순서대로",
    "corner": "구석에 가두다, 궁지에 몰다",
    "spelunking": "동굴 탐험",
    "anecdote": "일화, 짧은 이야기, 진술",
    "dumb down": "단순화하다, 쉽게 만들다",
    "mahalo": "감사합니다(하와이어)",
    "consonant": "자음, ~와 일치하는",
    "to save one’s life": "도저히(아무리 해도) ~할 수 없다",
    "schmear": "(베이글에 바르는) 스프레드, 바르다",
    "plausible": "그럴듯한",
    "glorified": "과장된, 겉만 번지르르한",
    "preface": "서문",
    "vis-à-vis": "대하여, ~에 관하여",
    "suffice": "충분하다",
    "sabbatical": "안식휴가",
    "kowtow": "굽실거리다, 비굴하게 굴다",
    "mediocre": "보통 수준의, 썩 좋지 않은",
    "get canned": "해고당하다",
    "mutilate": "훼손하다, 불구로 만들다",
    "workaday": "평범한, 일상적인",
    "mum’s the word": "비밀로 해, 입 다물어",
    "loom": "베틀, 직기 / 어렴풋이 나타나다, 불쑥 다가오다",
    "serape": "멕시코 전통 숄",
    "buckle up": "안전벨트를 매다",
    "crabby": "까다로운, 심술궂은",
    "rapture": "큰 기쁨, 황홀경",
    "to death": "~하게, 죽도록",
    "bobcat": "보브캣(스라소니), 소형 굴착기",
    "licorice": "감초, 감초 사탕",
    "shed": "흘리다, 벗다, (작은) 헛간",
    "fissionable": "핵분열성의",
    "yellow cake": "옐로케이크(우라늄 정광)",
    "have a fit": "노발대발하다",
    "no end": "끝없이, 대단히",
    "pluck": "뽑다, 용기",
    "pluck a nerve": "신경을 건드리다",
    "bounty": "현상금, 풍부함",
    "cobbler": "구두 수선공, 과일 파이",
    "spook": "겁주다, 유령",
    "snap out of it": "정신 차리다, 기운 내다",
    "get cracking": "서둘러 시작하다",
    "shove": "밀다, 떠밀다",
    "get off on the wrong side foot": "출발을 잘못하다, 처음부터 꼬이다",
    "elude": "피하다, 이해되지 않다",
}

words_5 = {
    "infantry": "보병",
    "infantry division": "보병 사단",
    "battalion": "대대(군부대 단위)",
    "cavalry": "기병, 기병대",
    "work something up": "자극하다, 불러일으키다, 준비하다",
    "aberration": "일탈, 이상",
    "quartet": "4인조, 4중주",
    "mishap": "불행한 사고, 작은 재난",
    "hot zone": "위험 지역",
    "neurotic": "신경증의, 불안한",
    "consolation": "위로, 위안",
    "be up for": "~할 의향이 있다, ~에 고려되고 있다",
    "pretext": "구실, 핑계",
    "double entendre": "이중 의미(특히 음담패설을 암시하는 표현)",
    "crude": "거친, 조잡한, 대충의",
    "point to": "지적하다, 가리키다",
    "poppy": "양귀비",
    "semiotics": "기호학",
    "door knob": "문 손잡이",
    "courtship": "구애, 교제",
    "tamper": "함부로 만지다, 위조하다, 간섭하다",
    "asymptotic": "점근적인, 점근선의",
    "haul": "끌다, 운반하다, 간신히 끌다",
    "delineate": "묘사하다, 윤곽을 그리다",
    "wound tight": "신경이 곤두선, 과민한",
    "pass up": "거절하다, 포기하다",
    "smother": "질식시키다, 억누르다",
    "blogsphere": "블로그 공간(인터넷상의 블로그 세계)",
    "go out on a limb": "위험을 무릅쓰다, 과감히 나서다",
    "foreseeable": "예측 가능한",
    "generic": "일반적인, 포괄적인",
    "platitude": "진부한 말, 상투어",
    "condiment": "양념, 조미료",
}
words_6 = {
    "preadolescent": "사춘기 이전의",
    "annihilate": "전멸시키다, 완파하다",
    "concise": "간결한",
    "frag": "(군대 속어) 수류탄으로 공격하다",
    "inquiry": "문의, 조사",
    "dork": "멍청이, 찌질이",
    "heads-up": "주의, 미리 알려줌",
    "quiver": "떨다, 전율하다 / 화살통",
    "sloppy": "엉성한, 지저분한",
    "effeminate": "(남자가) 여성스러운",
    "stethoscope": "청진기",
    "wasted": "술·약에 취한, 지쳐버린",
    "insensitive": "무신경한, 둔감한",
    "be entitled": "~할 자격이 있다",
    "primordial": "태고의, 원시의",
    "tickle one’s fancy": "흥미를 끌다, 마음에 들다",
    "back down": "물러서다, 굽히다",
    "assert": "주장하다, 단언하다",
    "scathing": "통렬한, 신랄한",
    "indictment": "기소, 고발",
    "halfling": "하플링(판타지 속 작은 종족, 예: 호빗) / 남자아이, 미성년의",
    "hop off": "이륙하다, 내리다, 뛰어내리다",
    "puffery": "과장 광고, 과대 선전",
    "opposable": "(손가락 등이) 마주 볼 수 있는, 대립 가능한",
    "leprechaun": "레프리콘(아일랜드 요정)",
    "put somebody in their place": "제자리를 찾게 하다, 버릇을 고치다, 본때를 보여주다",
}
words_7 = {
    "be through": "끝내다, 겪다",
    "mock": "비웃다, 조롱하다",
    "flawed": "결함이 있는",
    "yackety-yak": "쓸데없는 수다",
    "thong": "T자형 속옷, 슬리퍼(영국)",
    "bouillabaisse": "부야베스(프랑스 생선 스튜)",
    "dial down": "약화시키다, 완화하다, 줄이다",
    "outburst": "폭발, 격발, 급격한 증가",
    "regale": "즐겁게 해주다, 대접하다",
    "folksy": "서민적인, 소탈한",
    "good grief": "이런!, 세상에!",
    "horoscope": "별자리 운세",
    "notion": "개념, 생각",
    "sucky": "형편없는, 구린(속어)",
    "myriad": "무수한",
    "intricate": "복잡한, 정교한",
    "hamstring": "방해하다, 좌절시키다 / 햄스트링 근육",
    "cornered": "궁지에 몰린",
    "sore": "아픈, 화난",
    "sore loser": " 지고도 인정 못 하는 사람",
    "frankly": "솔직히",
    "succumb": "굴복하다, 압도되다",
    "fallacy": "틀린 생각, 오류",
    "ablution": "세정, 목욕 (종교적 의미로 씀)",
    "imperative": "필수적인, 명령적인",
    "marauder": "약탈자",
    "refer to": "~을 언급하다, 참조하다",
    "invalid": "무효의, 병약자",
    "robe": "예복, 가운",
    "loofah": "목욕용 해면",
    "mitt": "장갑, 손 보호대",
    "exfoliate": "각질을 제거하다",
    "why bother": "뭣하러 해?, 귀찮게 왜 해?",
    "repair to": "~로 가다",
    "weep": "울다, 눈물을 흘리다",
    "entree": "메인 요리(미국), 전채 요리(프랑스식)",
    "pull off": "성공해내다, 벗어나다",
    "predicated": "~에 근거한, 단언된",
    "put A ahead B": "A를 B보다 우선하다",
    "collective": "집단적인, 공동의",
    "punishable": "처벌할 수 있는",
    "portray": "묘사하다, 그리다",
    "semblance": "겉모습, 외관",
    "nudity": "나체, 벌거벗음",
    "hump": "혹, 혹처럼 솟은 것 / 성행위를 속어로",
    "middle ground": "중간 지점, 절충안",
    "putz": "바보, 얼간이(속어, 특히 유대계 영어)",
    "take a tone": "특정한 어조로 말하다",
    "bark up the wrong tree": "헛다리를 짚다",
    "cloak": "망토, 은폐하다",
}
words_8 = {
    "honorary": "명예의, 명예직의",
    "about/on your person": "몸에 지니고 있는",
    "crotch": "샅, 사타구니",
    "monsoon": "우기, 장마",
    "meddle": "간섭하다, 참견하다",
    "aspiration": "열망, 포부 / 흡입",
    "marry somebody off": "결혼시키다, 시집·장가 보내다",
    "ethnicity": "민족, 민족적 배경",
    "planetarium": "천문관, 플라네타리움",
    "rightly": "당연히, 올바르게",
    "feeler": "더듬이 / 타진, 탐색",
    "pushy": "강압적인, 억지가 센",
    "won’t hear the end of it": "계속 잔소리·불평을 듣게 될 것이다",
    "get the hang of something": "요령을 터득하다",
    "proficiency": "능숙, 숙달",
    "carefree": "근심 없는, 속 편한",
    "peewee": "아주 작은 것 / 꼬마",
    "Gynecologist": "부인과 의사",
    "showdown": "결전, 최종 대결",
    "hunky": "건장하고 잘생긴 (남자)",
    "tend": "돌보다 / ~하는 경향이 있다",
    "obnoxious": "불쾌한, 밉살스러운",
    "vestigial": "흔적만 남은, 퇴화한",
    "mock": "조롱하다, 흉내내다",
    "embodiment": "화신, 전형, 구현",
    "ebony": "흑단 / 새까만",
    "wrath": "격노, 분노",
    "intent": "의도, 목적",
    "for all intents and purposes": "사실상, 모든 면에서",
    "get off my case": "잔소리 좀 그만해, 나한테 좀 그만 참견해",
    "behead": "목을 베다, 참수하다",
    "chick": "병아리 / 아가씨(속어)",
    "funny man": "익살꾼, 개그맨",
}
words_9 = {
    "bounce off": "의견을 물어보다, ~에 부딪혀 튕겨 나오다",
    "geosynchronous": "지구와 동기화된, 정지궤도의",
    "goose bumps": "소름",
    "goose pimples": "소름",
    "pimple": "여드름",
    "ripped": "근육질의, 탄탄한 / 찢어진",
    "rabbi": "랍비(유대교 성직자)",
    "drill down": "세부적으로 파고들다, 심층 분석하다",
    "bed rock": "기반암, 기초, 근본",
    "drag coefficient": "항력 계수",
    "tassel": "술 장식, 태슬",
    "not to put too fine a point on it": "솔직히 말하자면, 직설적으로 말하면",
    "throw somebody a bone": "~를 돕는 시늉만 하다",
    "corduroy": "코듀로이(골덴 직물)",
    "bat crap": "(속어) 미친, 제정신 아닌 (보통 bat-crap crazy)",
    "paisley": "페이즐리 무늬",
    "growth spurt": "급성장기, 성장 급등기",
    "pope": "교황",
    "turmoil": "혼란, 소란",
    "hunch": "예감 (luck과 hunch의 조합)",
    "pander": "나쁜 욕망을 충족시키다",
    "undignified": "위엄 없는, 품위 없는",
    "condescension": "겸손한 체함, 생색내는 태도",
    "torment": "고통, 고통을 주다",
    "insecurity": "불안감",
    "egotist": "이기주의자, 자기 중심적인 사람",
    "settle for": "마지못해 ~을 택하다, ~에 만족하다",
    "nutcase": "미치광이, 괴짜",
    "run something over": "~을 차로 치다 / ~을 훑어보다",
    "uncalled for": "부적절한, 필요 없는",
    "clip fingernail": "손톱을 깎다",
}
words_10 = {
    "why bother to": "굳이 ~할 필요 있나?, 왜 수고를 해?",
    "kinky": "색다른, 변태적인 / 꼬불꼬불한",
    "moot": "논란의 여지가 있는 / 무의미한(영국·미국 용법 차이 있음)",
    "vocation": "직업, 천직",
    "avocation": "부업, 취미",
    "ruse": "계략, 책략",
    "pants on fire": "거짓말이 뻔한 (liar, liar, pants on fire!)",
    "trousers": "바지(영국식)",
    "strong suit": "강점, 장기",
    "deceitful": "기만적인, 사기의",
    "turn on": "~에 좌우되다 / 자극하다, 흥분시키다",
    "laughable": "우스꽝스러운, 가소로운",
    "exquisitely": "절묘하게, 정교하게",
    "convoluted": "복잡한, 뒤얽힌",
    "unravel": "풀다, 해명하다",
    "depict": "묘사하다, 그리다",
    "descent into": "~로 빠져듦, 몰락",
    "wee hours": "한밤중, 새벽녘",
    "wrung out": "몹시 지친, 탈진한",
    "wring out": "짜내다, 쥐어짜다",
    "drug-addled": "약에 취한, 약물로 정신이 흐린",
    "addled": "혼란스러운, 제정신이 아닌",
    "bogart": "혼자 차지하다 (속어, 특히 담배·마약류)",
    "hole up": "숨다, 은둔하다",
    "huff": "분노, 씩씩거림",
    "huffing": "흡입 마약 행위 / 씩씩거리며 숨쉬기",
    "ocean liner": "대형 여객선",
    "gripping": "손에 땀을 쥐게 하는, 흥미진진한",
    "I’m game": "나 할래, 나도 동의해",
    "shotgun": "자동차 조수석 / (미국 속어) ‘내가 먼저 할게’",
    "iffy": "불확실한, 애매한",
    "first mate": "1등 항해사",
    "quintessential": "전형적인, 본질적인",
    "rebel": "반역자, 반항하다",
    "predicament": "곤경, 궁지",
    "deceit": "속임수, 기만",
    "au contraire": "반대로, 천만에 (프랑스어 표현)",
    "brat": "버릇없는 애",
    "pop psychology": "대중 심리학",
    "bourgeois": "중산층의, 속물적인",
    "abused": "학대받은, 남용된",
    "chaplain": "군대·학교 등의 목사, 성직자",
    "fleabag": "허름한 여관 / 더러운 것",
    "cusp": "전환점, 경계",
    "mongrel": "잡종, 혼혈",
    "shove": "거칠게 밀다",
    "snort": "코웃음치다 / 코로 흡입하다",
}
words_11 = {
    "humble": "겸손한, 소박한",
    "at hand": "가까이에, 곧 있을",
    "germophobe": "세균 공포증 환자",
    "Lysol": "라이솔(소독제 브랜드)",
    "polish off": "뚝딱 해치우다, 다 먹어치우다",
    "apricot": "살구, 살구색",
    "get ahead": "출세하다, 성공하다",
    "get ahead of something": "~보다 앞서다, 앞질러 가다",
    "typhoid": "장티푸스",
    "corn-husker": "옥수수 껍질 벗기는 사람 / 네브래스카 주의 별명",
    "comatose": "혼수 상태의, 극도로 무기력한",
    "batter": "반죽 / 때리다, 연타하다",
    "comforter": "이불 / 위로하는 사람",
    "ungodly hour": "말도 안 되는 시간, 새벽같이 이른 시간",
    "ungodly": "끔찍한, 말도 안 되는",
    "affirmative": "긍정의, 찬성의",
    "put in place": "제자리에 두다 / 시행하다 / 단속하다",
    "lay low": "쓰러뜨리다, 죽이다, 패배시키다/ 몸을 숨기다, 잠잠히 지내다",
    "negatory": "부정적인, (무전·군사) 아니다",
    "apiece": "각자, 하나당",
    "febrile delirium": "열성 섬망",
    "frankfurter": "프랑크푸르트식 소시지",
    "crouton": "수프·샐러드용 작은 빵조각",
    "shout somebody down": "고함쳐서 상대 목소리를 묻어버리다",
    "pass out": "기절하다 / 나눠주다",
    "breach": "위반, 침해, 위반하다",
    "jeopardy": "위험, 위기",
    "paw": "(동물의) 발 / 손으로 더듬다",
    "stinking": "고약한 냄새가 나는 / 형편없는",
    "bad check": "부도 수표",
    "blitzkrieg": "기습공격",
    "cinder": "재, 타다 남은 것",
    "cinder block": "시멘트 블록",
    "ground rule": "기본 규칙",
    "crap out": "망치다, 작동이 멈추다",
    "the crap out of": "몹시, 심하게 (강조 표현)",
    "whiny": "짜증 섞은, 칭얼대는",
    "snot": "콧물 / 건방진 놈",
    "full blown": "본격적인, 만개한, 완전한",
    "mat": "엉겨붙은 것",
    "register": "등록하다, 감지하다",
    "set something off": "일으키다, 유발하다",
    "bearing": "태도, 자세 / 관련, 영향",
    "rat bastard": "비열한 놈, 개자식(속어)",
    "baster": "주방용 육즙 스포이드",
    "Tupperware": "타파웨어(플라스틱 밀폐 용기 브랜드)",
}
words_12 = {
    "lay it on me": "말해봐, 내게 알려줘",
    "How about that": "그거 참, 정말이야?",
    "disintegrate": "분해되다, 붕괴하다",
    "sought often": "자주 추구된, 수요가 많은",
    "seek after": "~을 추구하다",
    "tunnel out": "굴을 파서 빠져나가다",
    "show someone around": "~에게 안내하다",
    "look the other way": "모른 척하다",
    "grant money": "보조금",
    "smuggle": "밀수하다",
    "preposition": "전치사",
    "rec center": "레크리에이션 센터, 지역 복지관",
    "nautilus": "앵무조개",
    "startling": "깜짝 놀랄, 놀라운",
    "obnoxious": "불쾌한, 밉살스러운",
    "tale of woe": "비탄의 이야기",
    "get to": "~에 도착하다 / 짜증나게 하다 / 영향을 미치다",
    "come along": "함께 가다, 나타나다",
    "asterisk": "별표(*)",
    "pubescent": "사춘기의",
    "wunderkind": "신동, 천재 아동",
    "cease": "중단하다",
    "render": "만들다, 주다, 표현하다",
    "schematic": "개략적인, 도식적인",
    "hunch": "예감, 직감",
    "guess": "추측하다",
    "payload": "화물, 탑재량 / 유효 하중",
    "apparatus": "기구, 장치",
    "rest on": "~에 달려 있다, ~에 의존하다",
    "diploma": "졸업장",
    "cogent": "설득력 있는",
    "derail": "탈선하다, (계획을) 좌절시키다",
    "put out a spread": "푸짐하게 차려내다",
    "man of the hour": "주목받는 인물, 화제의 인물",
    "wailing wall": "통곡의 벽 (예루살렘 성지)",
    "jock": "운동광, 운동선수",
    "set-up": "계략, 준비, 설치",
    "puke": "토하다",
    "chubby": "통통한",
    "move in": "이사 들어오다, 개입하다",
    "moon over": "~생각에 넋을 맇다",
    "on end": "계속해서, 곧추서서",
    "uncalled for": "부적절한, 불필요한",
    "valedictorian": "졸업생 대표 연설자(수석 졸업생)",
    "ado": "야단법석, 소동",
    "by virtue of": "~ 덕분에, ~에 의하여",
    "naivete": "순진함, 천진난만함",
    "inexplicable": "설명할 수 없는, 불가사의한",
    "fall prey to": "~의 희생물이 되다",
    "step in": "개입하다",
    "baffle": "좌절시키다, 당황하게 하다",
    "repulse": "격퇴하다, 물리치다 / 혐오감을 주다",
    "yutz": "바보, 얼간이(속어, 유대계 영어)",
    "off-putting": "불쾌한, 거슬리는",
    "ticket": "벌금 딱지",
    "frisk": "몸수색하다, 수색",
}
words_13 = {
    "shapely": "균형 잡힌, 몸매가 좋은",
    "How come": "어째서, 왜",
    "nail polish": "매니큐어, 손톱 광택제",
    "field": "분야, 들판 / 현장에 내보내다",
    "gig": "공연, 임시 일자리",
    "count me out": "난 빼줘",
    "tawdry": "번지르르하지만 싸구려의",
    "Pictionary": "피셔너리(그림으로 맞추는 게임)",
    "boggle": "주춤하다",
    "chuppah": "유대교 혼례 천막",
    "bobsled": "봅슬레이",
    "dying words": "임종의 말, 유언",
    "perpetual": "영구적인, 끊임없는",
    "heads-up": "주의 환기, 미리 알림",
    "fierce": "사나운, 맹렬한",
    "gram for gram": "그램 단위로 비교하면",
    "incinerate": "소각하다, 태워 없애다",
    "magnifying glass": "돋보기",
    "point of order": "의사진행 발언, 이의 있습니다",
    "unanimous": "만장일치의",
    "move": "제안하다",
    "emblazon": "선명히 새기다, 장식하다",
    "yield": "양보하다, 산출하다",
    "fire away": "(질문을) 시작하다, 말해라",
    "glimpse": "흘끗 봄, 어렴풋이 알아차림",
    "salt": "소금 / 소금 치다",
    "eve": "전날, 전야",
    "douche": "질 세정 / (속어) 공격적이고 무례한 사람",
    "klatch": "수다 모임(특히 커피 모임)",
    "chutney": "처트니(인도식 조미료/소스)",
    "sack up": "용기를 내다(속어)",
    "in the sack": "잠자리에서, 성적으로",
    "hit that thing": "그 일을 해내다 / (속어) 성관계를 가지다",
    "contort": "뒤틀다, 비틀다, 뒤틀리다",
    "agony": "극심한 고통",
    "rest assured": "확신하다",
    "idiosyncrasy": "특이한 성격, 개성, 특이함",
    "confidentiality": "비밀 유지",
    "dilepton": "전자기 상호작용 입자쌍(물리학 용어)",
    "shm-": "비꼬아 반복하는 접두(예: fancy-shmancy)",
    "mano a mano": "일대일로, 정면 승부로",
    "misogynistic": "여성 혐오적인",
    "single-handed": "혼자의 힘으로",
    "adhesive": "접착제, 접착성의",
    "projectile": "투사체, 발사체",
    "trajectory": "탄도, 궤적",
    "preliminary": "예비의, 사전 준비의",
    "he’s got squat": "아무것도 없다, 가진 게 없다",
    "janitor": "관리인, 수위",
    "iron fist": "철권, 강압적 통치",
    "forfeit": "박탈, 몰수 / 벌로 잃다",
    "settle": "해결하다, 정착하다, 결정하다",
    "once and for all": "최종적으로, 단호히",
    "alumnus": "남자 졸업생",
    "alumna": "여자 졸업생",
    "alum": "졸업생(남녀 구분 없는 구어체)",
}
words_14 = {
    "unmitigated": "완전한, 전적인 (주로 부정적 맥락에서)",
    "culinary": "요리의, 음식 조리와 관련된",
    "auction off": "경매로 팔다",
    "prop": "영화소품",
    "bid on": "입찰하다",
    "spur of the moment": "충동적으로, 즉흥적으로",
    "memorabilia": "기념품, 수집품",
    "work out": "운동하다 / 잘 되다, 해결하다 / 계산하다, 산출하다",
    "on a regular basis": "정기적으로",
    "troubleshoot": "문제를 해결하다, 고장 원인을 찾다",
    "neat": "깔끔한, 멋진 / (미국) 멋져!",
    "running late": "늦어지고 있는",
    "stairwell": "계단 통로",
    "for what it’s worth": "그게 가치가 있을지 몰라도 (참고로 말하자면)",
    "by far": "단연코, 훨씬",
    "splinter": "쪼개진 조각 / 쪼개지다",
    "faction": "파벌, 당파",
    "Subterranean": "지하의",
    "feast": "잔치, 성찬",
    "dwell": "살다, 거주하다",
    "chick": "병아리 / 아가씨(속어)",
    "lame": "한심한, 구차한, 설득력 없는",
    "ground rule": "기본 규칙",
    "bimonthly": "격월의(두 달에 한 번) / 월 2회의(문맥 따라 다름)",
    "cloak": "망토 / 은폐하다",
    "reckoning": "심판, 계산, 판단",
    "skin": "피부가 까지다, (가죽을)벗기다",
    "fix up": "수리하다, 손보다 / 만남을 주선하다 / 마련해주다",
    "demeanor": "태도, 품행",
    "pick up on": "깨닫다, 주목하다 / 다시 언급하다",
    "woo": "구애하다, 설득하려 애쓰다",
    "predate": "~보다 앞서다",
    "stand on": "~에 근거하다 / 주장하다",
    "hook up with somebody": "~와 만나서 시간을 보내다, 관계를 맺다 (비격식)",
    "collectables": "수집할 가치가 있는 물건",
    "lot": "부지, 구역 / 제비뽑기 / 주차장",
    "throw in": "덤으로 주다 / 끼워 넣다",
    "dibs": "우선권 (내 거야!)",
    "look up": "찾아보다 / (상황이) 나아지다",
    "feline": "고양잇과의, 고양이 같은",
    "frolic": "즐겁게 뛰놀다, 장난치다",
}
words_15 = {
    "no guts": "겁쟁이, 배짱이 없음",
    "agoraphobia": "광장 공포증, 열린 공간에 대한 두려움",
    "bulletin board": "게시판",
    "brief": "간단한, 짧은 / 요약",
    "droll": "우스꽝스러운, 익살스러운",
    "furnace": "용광로, 화덕 / 난방용 보일러",
    "crooked": "구부러진, 부정직한",
    "quizzical": "어리둥절한, 우스꽝스러운 듯한",
    "fraternal": "형제의, 우애의",
    "fraternal twins": "이란성 쌍둥이",
    "gherkin": "작은 오이, 피클용 오이",
    "interject": "불쑥 끼어들다",
    "deem": "~라고 여기다, 생각하다",
    "girth": "허리 둘레, 둘레 치수",
    "affluence": "풍요, 부유",
    "detour": "우회로, 돌아가는 길",
    "loin": "허리, 허릿살",
    "posterity": "후세, 자손",
    "squabble": "옥신각신하다",
    "flatulent": "방귀가 잦은 / 허풍 떠는",
    "stake": "말뚝, 지분, 이해관계 / 걸다",
    "pimp out": "매춘하다, 착취하다",
    "mediocre": "보통의, 그저 그런",
    "freckling": "주근깨가 있음",
    "sole": "유일한 / 발바닥, 발바닥 살",
    "suitor": "구혼자",
    "cryogenic": "저온의, 극저온에서 작동하는",
    "delude": "속이다, 현혹하다",
    "you are in for a treat": "좋은 걸 경험하게 될 거야",
    "brag": "자랑하다",
}
words_16 = {
    "school": "훈련시키다, 교육시키다",
    "agility": "민첩함",
    "agile": "민첩한, 날렵한",
    "cut it out": "그만해!",
    "stalemate": "교착 상태, 막다름",
    "scrape": "긁다, 긁힘 / 곤경",
    "horoscope": "별자리 운세",
    "rant": "고함치다, 호통치다",
    "for the record": "기록을 위해 말하자면, 참고로 말하자면",
    "concise": "간결한",
    "meticulous": "세심한, 꼼꼼한",
    "hokum": "허튼소리, 터무니없는 것",
    "taurus": "황소자리",
    "chitchat": "잡담",
    "endeavor": "노력, 노력하다, 시도하다",
    "hell freezes over": "절대 일어나지 않을 때까지, 결코",
    "anguish": "극심한 고통, 괴로움",
    "comical": "웃기는, 우스꽝스러운",
    "blindfold": "눈가리개, 눈을 가리다",
    "grotesque": "기괴한",
    "frivolity": "경박함, 천박함",
    "frivolous": "경박한, 하찮은",
    "conspirator": "공모자, 음모를 꾸미는 사람",
    "institution": "기관, 제도",
    "laborious": "힘든, 고된",
    "body double": "대역 배우",
    "hamper": "방해하다 / 바구니",
    "wholesale": "도매 / 대규모의, 대량의",
    "hook up": "연결하다, 접속하다 / 엮이다",
    "stall": "지연시키다, 멎다 / 가판대",
    "I don’t need your attitude": "그런 태도 보일 필요 없어, 건방지게 굴지 마",
    "thy": "그대의 (고어, 시적 표현)",
    "gurney": "환자 운반용 들것, 바퀴 달린 침대",
    "Aries": "양자리",
    "Taurus": "황소자리",
    "Gemini": "쌍둥이자리",
    "Cancer": "게자리",
    "Leo": "사자자리",
    "Virgo": "처녀자리",
    "Libra": "천칭자리",
    "Scorpio": "전갈자리",
    "Sagittarius": "사수자리",
    "Capricorn": "염소자리",
    "Aquarius": "물병자리",
    "Pisces": "물고기자리",
}
words_17 = {
    "idiosyncrasy": "특이한 성격, 개성, 특이한 습관",
    "pass off": "행해지다",
    "pass off as": "~인 척하다, ~로 속이다",
    "drop dead": "당장 꺼져! / 뻗어 죽다",
    "credence": "믿음, 신용",
    "intimate": "친밀한 / 넌지시 알리다",
    "cop a feel": "추행하다, 동의 없이 만지다(속어)",
    "damsel": "처녀",
    "a damsel in distress": "위기에 처한 아가씨",
    "chivalry": "기사도, 정중함",
    "knighted": "기사 작위를 받은",
    "penitentiary": "교도소",
    "affectionate": "애정 어린, 다정한",
    "locale": "장소, 현장",
    "rendition": "연주, 공연 / 번역 / (특히 외국인 범죄자) 송환",
    "compelling": "주목하지 않을 수 없는, 강력한",
    "that’s the spirit": "바로 그거야! (격려 표현)",
    "slough": "허물, 진창 / 벗겨내다, 탈피하다",
    "noxious": "유해한, 해로운",
    "through the looking glass": "이상한 나라에 온 듯한, 현실과 반대인 세계",
    "dispersion": "분산, 흩어짐",
    "informed choice": "충분히 알고 내린 선택",
    "fling": "가벼운 연애 / 던지다",
    "draft": "초안 / 징병 / (공기) 외풍",
    "divert": "전환하다, 다른 데로 돌리다",
    "vial": "작은 병, 유리병",
    "psychic": "심령의, 초자연적인, 심령술사",
    "stuffing": "속(쿠션·봉제 인형·칠면조 속재료 등)",
    "redundancy": "불필요한 중복 / (英) 정리해고",
    "nauseous": "메스꺼운",
    "progeny": "자손, 후예", 
}
