name = "Season 2"
type = "TV show"
order = 2

words_1 = {
    "acidophilus": "애시도필러스, 유산균의 한 종류 (소화 건강 보조에 쓰임)",
    "thickness": "두께, 두터움, 걸쭉함",
    "wing it": "즉흥적으로 하다, 준비 없이 해내다",
    "exploit": "위업, 공적 / 착취하다, 부당하게 이용하다",
    "lame": "절름발이의 / 시시한, 별로인, 설득력없는",
    "impromptu": "즉흥적인, 준비 없는",
    "clench": "꽉 쥐다, 이를 악물다",
    "as to": "~에 관해서, ~에 대해",
    "brainiac": "엄청 똑똑한 사람, 천재",
    "covenant": "계약, 약속 (특히 법적·종교적 의미)",
    "impose": "부과하다, 강요하다",
    "ex-post": "사후의, 일이 끝난 뒤의",
    "basis": "기초, 근거",
    "facto": "(de facto에서) 사실상의",
    "homonymic": "동음이의의, 동철이의의 (발음이나 철자가 같은 다른 단어)",
    "arachnid": "거미류 (거미·전갈 등 절지동물)",
    "phrase": "구, 숙어, 표현, 표현하다",
    "dizzly": "어지러운, 현기증 나는 (dizzy에서 파생)",
    "arbitrary": "임의의, 제멋대로의, 독단적인",
    "axiomatic": "자명한, 당연한",
    "plastination": "플라스티네이션 (시체 보존 처리 기술)",
    "harmless": "무해한, 해롭지 않은, 악의없는",
    "rinse": "헹구다, 씻어내다",
    "thermostat": "온도조절기, 자동 온도 조절 장치",
    "cilantro": "고수(잎) (허브, 향신료)",
    "subvert": "전복시키다, 파괴하다",
    "leprous": "나병(한센병)의 / 병든 듯한",
    "you’re it": "술래잡기에서 ‘네가 술래야’",
    "roughhouse": "떠들썩하게 장난치다, 난폭하게 굴다",
    "sleepover": "밤샘 파티, 친구 집에서 자고 오는 것",
    "comfy": "편안한, 아늑한 (comfortable의 구어체)",
    "meh": "그저 그래, 별로 (무심한 태도 표현)",
    "unnerve": "긴장시키다, 불안하게 하다",
    "derivative": "파생물, 파생적인 / 독창성 없는",
    "drug": "약을 타다, 약을 주입하다",
    "take it on one’s grave": "죽을 때까지 비밀로 하다",
    "paralegal": "법률 보조원, 변호사 보조인",
}

words_2 = {
    "rife": "만연한, 흔한 (특히 안 좋은 것이 널리 퍼져 있는)",
    "tavern": "선술집, 술집 (옛날 표현)",
    "flagon": "술병, 큰 주전자",
    "mead": "벌꿀주 (꿀과 물로 만든 술)",
    "nitpick": "사소한 것까지 트집잡다",
    "nit": "서캐 / 아주 작은 것, 사소한 것",
    "lace up": "끈을 묶다 (특히 신발 끈)",
    "bosom": "가슴, 품",
    "howdy": "안녕! (Howdy do?의 줄임, 미국 구어체)",
    "huzzah": "만세! 환호!",
    "chain mail": "사슬 갑옷 (고대/중세의 갑옷)",
    "undergarment": "속옷",
    "sloppy": "엉성한, 지저분한, 대충 한",
    "smoking hot": "멋진",
    "I would hit that": "저 사람(상대)과 자고 싶다 (속어, 외설적 뉘앙스)",
    "lavatory": "화장실",
    "unattended": "내버려진, 관리되지 않은",
    "bout": "한 차례, 한 판, (병의) 발작",
    "futon": "이불, 요 (일본식 침구, 소파베드 뜻도 있음)",
    "arty": "예술가인 척하는, 허세 예술스러운",
    "artsy": "예술가 같은, 예술적으로 보이려는",
    "petting": "애무, 애정 표현 (특히 성적인 의미 포함)",
    "pernicious": "치명적인, 해로운",
    "merrier": "더 즐거운 (merry의 비교급)",
    "exile": "망명, 추방 / 망명자",
    "staircase": "계단, 계단 통로",
    "get this": "자, 들어봐 / 믿기 힘들겠지만 (강조 표현)",
    "abrupt": "갑작스러운, 퉁명스러운",
    "carton": "판지 상자, 종이팩 (우유팩 등), 한갑, 한통",
    "eccentric": "괴짜, 별난 / 별난",
    "viability": "실행 가능성, 생존 능력",
    "cloy": "물리게 하다, 싫증나게 하다",
    "repulse": "격퇴하다, 물리치다 / 혐오감을 주다",
    "jester": "광대 (중세 왕실의 어릿광대)",
    "anomaly": "이례적인 것, 예외, 변칙",
    "mix it up": "싸우다, 다투다 / 섞다",
    "archenemy": "숙적, 최대의 적",
    "belittle": "하찮게 여기다, 깎아내리다",
    "objection": "반대, 이의 제기",
    "ill-considered": "경솔한, 잘 생각하지 않은",
    "triumph": "승리, 업적",
    "gracious": "상냥한, 우아한 / (놀람 표현) 세상에!",
    "subpar": "기준 이하의, 보통 이하의",
    "balderdash": "허튼소리, 헛소리",
    "snort": "코웃음치다, 코로 흡입하다",
    "derision": "조롱, 비웃음"
}