name = "Joomiere"
type = "word"
order = 1

words_1 = {    
    "Merci": "고마워",
    "Merci beaucoup": "정말 고마워",
    "Merci infiniment": "대단히 고맙습니다",
    "De rien": "천만에요",
    "C'est normal": "별말씀을요, 당연한 일이에요",
    "Avec plaisir": "기꺼이요, 천만에요",

    "Ça va ?": "잘 지내?",
    "Comment allez-vous ?": "안녕하세요? (격식체)",
    "Tout va bien ?": "모든 게 잘 돼?",
    "Ça va.": "괜찮아, 잘 지내",
    "Je vais bien.": "저는 잘 지내요",
    "Et vous ? (Et toi ?)": "당신은요? (너는?)",

    "Pardon": "미안, 실례",
    "Désolé(e)": "죄송합니다, 미안해요",
    "Excusez-moi": "실례합니다",
    "Pas de problème.": "문제없어요",
    "Pas de souci.": "걱정하지 마세요",
    "Ce n'est pas grave.": "별일 아니에요",

    "Au revoir": "안녕히 가세요, 안녕히 계세요",
    "Salut": "안녕 (친근하게)",
    "À plus tard": "나중에 봐",
    "À ce soir": "오늘 저녁에 봐",
    "Bonne journée": "좋은 하루 보내세요",
    "Bonne soirée": "좋은 저녁 보내세요",

    "Bon courage": "힘내요, 용기를 가지세요",
    "Bon appétit": "맛있게 드세요",
    "Bon anniversaire": "생일 축하합니다",
    "Bon week-end": "즐거운 주말 보내세요",
    "Bonne année": "새해 복 많이 받으세요",
    "Bonne continuation": "앞으로도 잘 지내세요, 계속 힘내세요",

    "homme / femme": "남자 / 여자",
    "père / mère": "아버지 / 어머니",
    "frère / sœur": "형제 / 자매",
    "garçon / fille": "소년 / 소녀",
    "coq / poule": "수탉 / 암탉",

    "ami / amie": "남자 친구 / 여자 친구",
    "Coréen / Coréenne": "한국 남자 / 한국 여자",
    "Français / Française": "프랑스 남자 / 프랑스 여자",
    "étudiant / étudiante": "남학생 / 여학생",
    "chanteur / chanteuse": "가수(남자) / 가수(여자)",
    "cuisinier / cuisinière": "요리사(남자) / 요리사(여자)",
    "journaliste / journaliste": "기자(남자) / 기자(여자)",

    "soleil": "태양",
    "lune": "달",
    "arbre": "나무",
    "fleur": "꽃",
    "bateau": "배",
    "mer": "바다",
    "livre": "책",
    "maison": "집",
    "ciel": "하늘",
    "terre": "땅",
    "vin": "와인",
    "eau": "물",
    "courage": "용기",
    "patience": "인내",


    "livre / livres": "책 / 책들",
    "ami / amis": "친구 / 친구들",
    "ballon / ballons": "공 / 공들",
    "pays / pays": "나라 / 나라들 (단·복수 동일)",
    "choix / choix": "선택 / 선택들 (단·복수 동일)",
    "nez / nez": "코 / 코들 (단·복수 동일)",
    "manteau / manteaux": "코트 / 코트들",
    "chapeau / chapeaux": "모자 / 모자들",
    "animal / animaux": "동물 / 동물들",
    "journal / journaux": "신문 / 신문들",

    "un homme / des hommes": "남자 / 남자들",
    "une femme / des femmes": "여자 / 여자들",
    "un enfant / des enfants": "아이 / 아이들",
    "une école / des écoles": "학교 / 학교들",
    "un tapis / des tapis": "카펫 / 카펫들",
    "un ami / une amie / des amis": "남자 친구 / 여자 친구 / 친구들",
    "un étudiant / une étudiante / des étudiants": "남학생 / 여학생 / 학생들",

    "le crayon / les crayons": "연필 / 연필들",
    "la chaise / les chaises": "의자 / 의자들",
    "l'île / les îles": "섬 / 섬들",
    "l'hôtel / les hôtels": "호텔 / 호텔들",
    "le voisin / la voisine": "남자 이웃 / 여자 이웃",
    "les voisins / les voisines": "남자 이웃들 / 여자 이웃들",
    "le coiffeur / la coiffeuse": "남자 미용사 / 여자 미용사",
    "les coiffeurs / les coiffeuses": "남자 미용사들 / 여자 미용사들",
    "le Canadien / la Canadienne": "캐나다 남자 / 캐나다 여자",
    "les Canadiens / les Canadiennes": "캐나다 남자들 / 캐나다 여자들",
}
words_2 = {
    "du pain": "빵",
    "du fromage": "치즈",
    "du beurre": "버터",

    "de la viande": "고기",
    "de la salade": "샐러드",
    "de la glace": "아이스크림",

    "du sel": "소금",
    "du sucre": "설탕",
    "du poivre": "후추",

    "du café": "커피",
    "du lait": "우유",
    "de la bière": "맥주",

    "de l'argent": "돈",
    "de l'eau": "물",
    "de l'huile": "기름",

    "du courage": "용기",
    "de la chance": "운",

    "des épinards": "시금치",
    "des pâtes": "파스타",

    "un verre": "컵, 유리잔",
    "une lettre": "편지",
    "des fruits": "과일들",

    "le collier": "목걸이",
    "la bague": "반지",
    "les messages": "메시지들",

    "du thé": "차",
    "de la confiture": "잼",
    "de l'eau": "물",

    "On est là.": "우리는 거기에 있다 / 여기 있다.",
    "On est amis.": "우리는 친구다.",
    "En France, on aime le fromage.": "프랑스에서는 치즈를 좋아한다.",
    "En Corée, on aime le Kimchi.": "한국에서는 김치를 좋아한다.",
    "On frappe à la porte.": "누군가 문을 두드린다.",
    "On m'appelle.": "사람들이 나를 부른다 / 전화가 온다.",

    "Je suis Yuna.": "나는 유나다.",
    "Tu es médecin.": "너는 의사다.",
    "Elle est boulangère.": "그녀는 제빵사다.",
    "Nous sommes allemands.": "우리는 독일인이다.",
    "Vous êtes vietnamien.": "당신은 베트남인이다.",
    "Ils sont chrétiens.": "그들은 기독교인이다.",
    "Vous êtes bouddhiste.": "당신은 불교도이다.",
    "Elles sont touristes.": "그녀들은 관광객이다.",

    "C'est un jardin.": "이것은 정원이다.",
    "C'est une table.": "이것은 탁자이다.",
    "C'est le musée.": "이것은 그 박물관이다.",
    "C'est la voiture.": "이것은 그 자동차이다.",
    "C'est du pain.": "이것은 빵이다.",
    "C'est de la confiture.": "이것은 잼이다.",
    "C'est le garçon.": "이것은 그 소년이다.",
    "C'est la fille.": "이것은 그 소녀이다.",
    "C'est Delphine.": "이것은 델핀이다.",
    "C'est le professeur.": "이것은 그 선생님이다.",
    "C'est un client.": "이것은 어떤 손님이다.",
    "C'est une voisine.": "이것은 어떤 여자 이웃이다.",

    "Ce sont des tables.": "이것들은 (몇 개의) 탁자들이다.",
    "Ce sont des bouteilles.": "이것들은 (몇 개의) 병들이다.",
    "Ce sont des bus.": "이것들은 (몇 대의) 버스들이다.",
    "Ce sont des fleurs.": "이것들은 (몇 송이의) 꽃들이다.",
    "Ce sont les voitures.": "이것들은 그 자동차들이다.",
    "Ce sont les lettres.": "이것들은 그 편지들이다.",
    "Ce sont les filles.": "이것들은 그 여자아이들이다.",
    "Ce sont les garçons.": "이것들은 그 남자아이들이다.",
    "Ce sont des amis.": "이것들은 (몇 명의) 친구들이다.",
    "Ce sont Julie et Philippe.": "이 사람들은 줄리와 필리프이다.",
    "Ce sont monsieur Martin et madame Dubois.": "이분들은 마르탱 씨와 뒤부아 부인이다.",

    "Moi, je suis coréen.": "나, 나는 한국인이다.",
    "Toi, tu es Jean ?": "너, 너는 장이니?",
    "C'est lui !": "그 사람이다! / 바로 그 사람이다!",
    "Là-bas, c'est elle !": "저기, 저 사람이야!",
    "Vous !": "당신! / 여러분!",
    "C'est qui ? - Moi !": "누구야? - 나야!",
    "Avec toi": "너와 함께",
    "Je suis chez eux.": "나는 그들 집에 있어.",

}
words_3 = {
    "C'est moi.": "나다.",
    "C'est toi.": "너다.",
    "C'est vous.": "당신(들)이다.",

    "C'est à moi.": "내 거다.",
    "C'est à elle.": "그녀 거다.",

    "C'est pour vous.": "당신(들을) 위한 거다.",
    "C'est pour lui.": "그를 위한 거다.",

    "Après vous.": "당신 먼저 하세요.",

    "chez moi": "내 집에서",
    "Je suis chez lui.": "나는 그의 집에 있어.",

    "Et toi ?": "그리고 너는?",
    "Et vous ?": "그리고 당신(들은)?",

    "Je ne suis pas Minsoo.": "나는 민수가 아니다.",
    "Je ne suis pas coréen.": "나는 한국인이 아니다.",
    "Tu n'es pas cuisinière.": "너는 요리사가 아니다.",
    "Il n'est pas japonais.": "그는 일본인이 아니다.",
    "On n'est pas amis.": "우리는 친구가 아니다.",
    "Elle n'est pas française.": "그녀는 프랑스인이 아니다.",
    "Nous ne sommes pas professeurs.": "우리는 선생님이 아니다.",
    "Vous n'êtes pas coiffeur.": "당신은 미용사가 아니다.",
    "Ils ne sont pas chrétiens.": "그들은 기독교인이 아니다.",
    "Elles ne sont pas canadiennes.": "그녀들은 캐나다인이 아니다.",

    "Elle est allemande ?": "그녀는 독일인인가?",
    "C'est de la confiture ?": "그것은 잼인가?",
    "C'est Pierre ?": "그것은 피에르인가?",
    "Es-tu chanteuse ?": "너는 가수인가?",
    "Êtes-vous français ?": "당신은 프랑스인입니까?",
    "Est-ce un livre ?": "그것은 책인가?",
    "Est-ce que c'est un jardin ?": "그것은 정원인가?",
    "Est-ce que vous êtes étudiant ?": "당신은 학생입니까?",
    "Est-ce qu'ils sont anglais ?": "그들은 영국인인가?",

    "Oui": "응, 그래",
    "Ouais": "어, 맞아 (비격식)",
    "OK": "오케이, 알았어",
    "D'accord": "알겠어, 좋아",
    "Bien sûr": "물론이지",
    "Ça marche.": "그거 괜찮아, 좋아",
    "Carrément": "당연하지, 완전히 그래",

    "Non": "아니",
    "Non, merci.": "아니요, 괜찮습니다",
    "Ça marche pas.": "그거 안 돼, 안 통해",
    "C'est bon.": "괜찮아, 됐어",
    "Pas du tout": "전혀 아니야",
    "Absolument pas": "절대 아니야",

    "bon": "좋은",
    "mauvais": "나쁜",
    "jeune": "젊은",
    "vieux": "늙은, 오래된",

    "petit": "작은",
    "grand": "큰",
    "beau": "아름다운",
    "nouveau": "새로운",

    "rouge": "빨간",
    "jaune": "노란",
    "vert": "초록색의",
    "bleu": "파란",

    "sucré": "단",
    "salé": "짠",
    "amer": "쓴",

    "heureux": "행복한",
    "timide": "소심한",
    "sérieux": "진지한",
    "surpris": "놀란",

    "le ciel bleu": "푸른 하늘",
    "un livre jaune": "노란 책",
    "du pain sucré": "단 빵",
    "du beurre salé": "짠 버터",
    "un garçon timide": "소심한 소년",

    "C'est un verre vert.": "이것은 초록색 컵이다",
    "C'est un homme sérieux.": "이 사람은 진지한 남자이다",
    "C'est un médicament amer.": "이것은 쓴 약이다",

    "C'est un beau pays.": "이것은 아름다운 나라이다",
    "C'est un mauvais produit.": "이것은 나쁜 제품이다",
    "Il est un grand garçon.": "그는 키 큰 소년이다",
    "Tu es un bon ami.": "너는 좋은 친구이다",

    "une belle maison": "아름다운 집",
    "une fille surprise": "놀란 소녀",
    "de la bière amère": "쓴 맥주",
    "une bonne idée": "좋은 생각",
    "une sauce sucrée": "단 소스",

    "des garçons surpris": "놀란 소년들",
    "des filles surprises": "놀란 소녀들",
    "des amis jeunes": "젊은 친구들",
    "de grands rêves": "큰 꿈들",
    "de grandes maisons": "큰 집들",
    "de petits livres": "작은 책들",
    "de nouveaux magasins": "새로운 가게들",

    "beau": "아름다운, 멋진 (남성 단수)",
    "bel": "아름다운, 멋진 (남성 단수, 모음 앞)",
    "belle": "아름다운, 멋진 (여성 단수)",
    "beaux": "아름다운, 멋진 (남성 복수)",
    "belles": "아름다운, 멋진 (여성 복수)",

    "nouveau": "새로운 (남성 단수)",
    "nouvel": "새로운 (남성 단수, 모음 앞)",
    "nouvelle": "새로운 (여성 단수)",
    "nouveaux": "새로운 (남성 복수)",
    "nouvelles": "새로운 (여성 복수)",

    "vieux": "늙은, 오래된 (남성 단수/복수)",
    "vieil": "늙은, 오래된 (남성 단수, 모음 앞)",
    "vieille": "늙은, 오래된 (여성 단수)",
    "vieilles": "늙은, 오래된 (여성 복수)",
}
words_4 = {
    "C'est vrai.": "그거 사실이야.",
    "C'est génial.": "정말 멋져.",
    "C'est top.": "최고야.",
    "C'est parfait.": "완벽해.",
    "C'est beau.": "아름다워.",

    "C'est salé.": "짜다.",
    "C'est sucré.": "달다.",
    "C'est gratuit?": "무료야?",
    "C'est bon?": "맛있어?",
    "C'est cher?": "비싸?",   

    "C'est très bon.": "아주 맛있다.",
    "C'est très bizarre.": "아주 이상하다.",
    "C'est vraiment salé.": "정말 짜다.",
    "C'est vraiment incroyable.": "정말 믿기 어렵다.",
    "C'est trop sucré.": "너무 달다.",
    "C'est trop drôle.": "너무 웃기다.",
    "C'est tellement génial.": "정말 멋지다.",
    "C'est tellement facile.": "정말 쉽다.",
    "Ce n'est pas très facile.": "그다지 쉽지 않다.",
    "Ce n'est pas très tôt.": "그다지 이르지 않다.",

    "un euro": "1유로",
    "trois euros": "3유로",
    "sept euros": "7유로",
    "un an": "1년",
    "deux ans": "2년",
    "huit ans": "8년",
    "une heure": "1시",
    "cinq heures": "5시",
    "six heures": "6시",

    "Il est une heure.": "1시입니다.",
    "Il est deux heures.": "2시입니다.",
    "Il est trois heures.": "3시입니다.",
    "Il est quatre heures.": "4시입니다.",
    "Il est cinq heures.": "5시입니다.",
    "Il est six heures.": "6시입니다.",
    "Il est sept heures.": "7시입니다.",
    "Il est huit heures.": "8시입니다.",
    "Il est neuf heures.": "9시입니다.",
    "Il est dix heures.": "10시입니다.",
    "Il est onze heures.": "11시입니다.",
    "Il est douze heures.": "12시입니다.",

    "premier / première": "첫 번째",
    "deuxième": "두 번째",
    "troisième": "세 번째",
    "quatrième": "네 번째",
    "cinquième": "다섯 번째",
    "sixième": "여섯 번째",
    "septième": "일곱 번째",
    "huitième": "여덟 번째",
    "neuvième": "아홉 번째",
    "dixième": "열 번째",

    "ce livre": "이 책",
    "ce crayon": "이 연필",
    "cette salade": "이 샐러드",
    "cette clé": "이 열쇠",
    "ces pommes": "이 사과들",
    "ces gens": "이 사람들",
    "cet hôtel": "이 호텔",
    "cet amour": "이 사랑",

    "ce matin": "오늘 아침",
    "ce soir": "오늘 저녁",
    "cet après-midi": "오늘 오후",
    "cette semaine": "이번 주",
    "cette année": "올해",
    "ces jours-ci": "요즘",

    "C'est bon ! – Cela ?": "좋아! – 그거?",
    "Cela est génial !": "그건 멋져!",
    "J'aime cela.": "나는 그것을 좋아해.",
    "J'aime ça.": "난 그거 좋아해.",
    "Ça y est.": "됐다. / 드디어!",
    "Ça suffit.": "그만해. / 충분해.",

    "mon piano": "나의 피아노",
    "ma voiture": "나의 자동차",
    "mes yeux": "나의 눈들",

    "ton opinion": "너의 의견",
    "ta fille": "너의 딸",
    "tes cheveux": "너의 머리카락",

    "son amie": "그/그녀의 여자 친구",
    "ses efforts": "그/그녀의 노력들",

    "notre école": "우리의 학교",
    "votre histoire": "당신의 이야기",
    "leur chanson": "그들의 노래",

    "le mien": "나의 것 (남성 단수)",
    "la mienne": "나의 것 (여성 단수)",
    "les miens": "나의 것 (남성 복수)",
    "les miennes": "나의 것 (여성 복수)",

    "le tien": "너의 것 (남성 단수)",
    "la tienne": "너의 것 (여성 단수)",
    "les tiens": "너의 것 (남성 복수)",
    "les tiennes": "너의 것 (여성 복수)",

    "le sien": "그/그녀의 것 (남성 단수)",
    "la sienne": "그/그녀의 것 (여성 단수)",
    "les siens": "그/그녀의 것 (남성 복수)",
    "les siennes": "그/그녀의 것 (여성 복수)",

    "le nôtre": "우리의 것 (남성 단수)",
    "la nôtre": "우리의 것 (여성 단수)",
    "les nôtres": "우리의 것 (복수)",

    "le vôtre": "당신(들)의 것 (남성 단수)",
    "la vôtre": "당신(들)의 것 (여성 단수)",
    "les vôtres": "당신(들)의 것 (복수)",

    "le leur": "그(녀)들의 것 (남성 단수)",
    "la leur": "그(녀)들의 것 (여성 단수)",
    "les leurs": "그(녀)들의 것 (복수)",
}


