name = "Joomiere"
type = "word"
order = 1

words_1 = {    
    "Merci": "고마워",
    "Merci beaucoup": "정말 고마워",
    "Merci infiniment": "대단히 고맙습니다",
    "De rien": "천만에요",
    "C'est normal": "별말씀을요, 당연한 일이에요",
    "Avec plaisir": "기꺼이요, 천만에요",

    "Ça va ?": "잘 지내?",
    "Comment allez-vous ?": "안녕하세요? (격식체)",
    "Tout va bien ?": "모든 게 잘 돼?",
    "Ça va.": "괜찮아, 잘 지내",
    "Je vais bien.": "저는 잘 지내요",
    "Et vous ? (Et toi ?)": "당신은요? (너는?)",

    "Pardon": "미안, 실례",
    "Désolé(e)": "죄송합니다, 미안해요",
    "Excusez-moi": "실례합니다",
    "Pas de problème.": "문제없어요",
    "Pas de souci.": "걱정하지 마세요",
    "Ce n'est pas grave.": "별일 아니에요",

    "Au revoir": "안녕히 가세요, 안녕히 계세요",
    "Salut": "안녕 (친근하게)",
    "À plus tard": "나중에 봐",
    "À ce soir": "오늘 저녁에 봐",
    "Bonne journée": "좋은 하루 보내세요",
    "Bonne soirée": "좋은 저녁 보내세요",

    "Bon courage": "힘내요, 용기를 가지세요",
    "Bon appétit": "맛있게 드세요",
    "Bon anniversaire": "생일 축하합니다",
    "Bon week-end": "즐거운 주말 보내세요",
    "Bonne année": "새해 복 많이 받으세요",
    "Bonne continuation": "앞으로도 잘 지내세요, 계속 힘내세요",

    "homme / femme": "남자 / 여자",
    "père / mère": "아버지 / 어머니",
    "frère / sœur": "형제 / 자매",
    "garçon / fille": "소년 / 소녀",
    "coq / poule": "수탉 / 암탉",

    "ami / amie": "남자 친구 / 여자 친구",
    "Coréen / Coréenne": "한국 남자 / 한국 여자",
    "Français / Française": "프랑스 남자 / 프랑스 여자",
    "étudiant / étudiante": "남학생 / 여학생",
    "chanteur / chanteuse": "가수(남자) / 가수(여자)",
    "cuisinier / cuisinière": "요리사(남자) / 요리사(여자)",
    "journaliste / journaliste": "기자(남자) / 기자(여자)",

    "soleil / lune": "태양 / 달",
    "arbre / fleur": "나무 / 꽃",
    "bateau / mer": "배 / 바다",
    "livre / maison": "책 / 집",
    "ciel / terre": "하늘 / 땅",
    "vin / eau": "와인 / 물",
    "courage / patience": "용기 / 인내",

    "livre / livres": "책 / 책들",
    "ami / amis": "친구 / 친구들",
    "ballon / ballons": "공 / 공들",
    "pays / pays": "나라 / 나라들 (단·복수 동일)",
    "choix / choix": "선택 / 선택들 (단·복수 동일)",
    "nez / nez": "코 / 코들 (단·복수 동일)",
    "manteau / manteaux": "코트 / 코트들",
    "chapeau / chapeaux": "모자 / 모자들",
    "animal / animaux": "동물 / 동물들",
    "journal / journaux": "신문 / 신문들",

    "un homme / des hommes": "남자 / 남자들",
    "une femme / des femmes": "여자 / 여자들",
    "un enfant / des enfants": "아이 / 아이들",
    "une école / des écoles": "학교 / 학교들",
    "un tapis / des tapis": "카펫 / 카펫들",
    "un ami / une amie / des amis": "남자 친구 / 여자 친구 / 친구들",
    "un étudiant / une étudiante / des étudiants": "남학생 / 여학생 / 학생들",

    "le crayon / les crayons": "연필 / 연필들",
    "la chaise / les chaises": "의자 / 의자들",
    "l'île / les îles": "섬 / 섬들",
    "l'hôtel / les hôtels": "호텔 / 호텔들",
    "le voisin / la voisine": "남자 이웃 / 여자 이웃",
    "les voisins / les voisines": "남자 이웃들 / 여자 이웃들",
    "le coiffeur / la coiffeuse": "남자 미용사 / 여자 미용사",
    "les coiffeurs / les coiffeuses": "남자 미용사들 / 여자 미용사들",
    "le Canadien / la Canadienne": "캐나다 남자 / 캐나다 여자",
    "les Canadiens / les Canadiennes": "캐나다 남자들 / 캐나다 여자들",

    "du pain / du fromage / du beurre": "빵 / 치즈 / 버터",
    "de la viande / de la salade / de la glace": "고기 / 샐러드 / 아이스크림",
    "du sel / du sucre / du poivre": "소금 / 설탕 / 후추",
    "du café / du lait / de la bière": "커피 / 우유 / 맥주",
    "de l'argent / de l'eau / de l'huile": "돈 / 물 / 기름",
    "du courage / de la chance": "용기 / 운",
    "des épinards / des pâtes": "시금치 / 파스타",
}

