name = "Nombre"
type = "word"
order = 1

words_1 = {
  "1": "un (앙)",
  "2": "deux (되)",
  "3": "trois (트ㅎ와)",
  "4": "quatre (카뜨ㅎ)",
  "5": "cinq (생ㅋ)",
  "6": "six (씨/시스)",
  "7": "sept (쎗)",
  "8": "huit (위)",
  "9": "neuf (느프)",
  "10": "dix (디스)",

  "11": "onze (옹즈)",
  "12": "douze (두즈)",
  "13": "treize (트ㅎ레즈)",
  "14": "quatorze (카또ㅎ즈)",
  "15": "quinze (캉즈)",
  "16": "seize (세즈)",
  "17": "dix-sept (디쎗)",
  "18": "dix-huit (디쥐)",
  "19": "dix-neuf (디즈느프)",
  "20": "vingt (방)",

  "21": "vingt et un (방 떼 앙)",
  "22": "vingt-deux (방 되)",
  "23": "vingt-trois (방 트ㅎ와)",
  "24": "vingt-quatre (방 카뜨ㅎ)",
  "25": "vingt-cinq (방 생ㅋ)",
  "26": "vingt-six (방 씨)",
  "27": "vingt-sept (방 쎗)",
  "28": "vingt-huit (방 위)",
  "29": "vingt-neuf (방 느프)",
  "30": "trente (트ㅎ앙뜨)",

  "31": "trente et un (트ㅎ앙뜨 떼 앙)",
  "32": "trente-deux (트ㅎ앙뜨 되)",
  "33": "trente-trois (트ㅎ앙뜨 트ㅎ와)",
  "34": "trente-quatre (트ㅎ앙뜨 카뜨ㅎ)",
  "35": "trente-cinq (트ㅎ앙뜨 생ㅋ)",
  "36": "trente-six (트ㅎ앙뜨 씨)",
  "37": "trente-sept (트ㅎ앙뜨 쎗)",
  "38": "trente-huit (트ㅎ앙뜨 위)",
  "39": "trente-neuf (트ㅎ앙뜨 느프)",
  "40": "quarante (카ㅎ앙뜨)",

  "41": "quarante et un (카ㅎ앙뜨 떼 앙)",
  "42": "quarante-deux (카ㅎ앙뜨 되)",
  "43": "quarante-trois (카ㅎ앙뜨 트ㅎ와)",
  "44": "quarante-quatre (카ㅎ앙뜨 카뜨ㅎ)",
  "45": "quarante-cinq (카ㅎ앙뜨 생ㅋ)",
  "46": "quarante-six (카ㅎ앙뜨 씨)",
  "47": "quarante-sept (카ㅎ앙뜨 쎗)",
  "48": "quarante-huit (카ㅎ앙뜨 위)",
  "49": "quarante-neuf (카ㅎ앙뜨 느프)",
  "50": "cinquante (쌍꽁뜨)",

  "51": "cinquante et un (쌍꽁뜨 떼 앙)",
  "52": "cinquante-deux (쌍꽁뜨 되)",
  "53": "cinquante-trois (쌍꽁뜨 트ㅎ와)",
  "54": "cinquante-quatre (쌍꽁뜨 카뜨ㅎ)",
  "55": "cinquante-cinq (쌍꽁뜨 생ㅋ)",
  "56": "cinquante-six (쌍꽁뜨 씨)",
  "57": "cinquante-sept (쌍꽁뜨 쎗)",
  "58": "cinquante-huit (쌍꽁뜨 위)",
  "59": "cinquante-neuf (쌍꽁뜨 느프)",
  "60": "soixante (수아쌍뜨)",

  "61": "soixante et un (수아쌍뜨 떼 앙)",
  "62": "soixante-deux (수아쌍뜨 되)",
  "63": "soixante-trois (수아쌍뜨 트ㅎ와)",
  "64": "soixante-quatre (수아쌍뜨 카뜨ㅎ)",
  "65": "soixante-cinq (수아쌍뜨 생ㅋ)",
  "66": "soixante-six (수아쌍뜨 씨)",
  "67": "soixante-sept (수아쌍뜨 쎗)",
  "68": "soixante-huit (수아쌍뜨 위)",
  "69": "soixante-neuf (수아쌍뜨 느프)",
  "70": "soixante-dix (수아쌍뜨 디스)",

  "71": "soixante et onze (수아쌍뜨 떼 옹즈)",
  "72": "soixante-douze (수아쌍뜨 두즈)",
  "73": "soixante-treize (수아쌍뜨 트ㅎ레즈)",
  "74": "soixante-quatorze (수아쌍뜨 카또ㅎ즈)",
  "75": "soixante-quinze (수아쌍뜨 캉즈)",
  "76": "soixante-seize (수아쌍뜨 세즈)",
  "77": "soixante-dix-sept (수아쌍뜨 디쎗)",
  "78": "soixante-dix-huit (수아쌍뜨 디쥐)",
  "79": "soixante-dix-neuf (수아쌍뜨 디즈느프)",
  "80": "quatre-vingts (까뜨ㅎ브앙)",

  "81": "quatre-vingt-un (까뜨ㅎ브앙 앙)",
  "82": "quatre-vingt-deux (까뜨ㅎ브앙 되)",
  "83": "quatre-vingt-trois (까뜨ㅎ브앙 트ㅎ와)",
  "84": "quatre-vingt-quatre (까뜨ㅎ브앙 카뜨ㅎ)",
  "85": "quatre-vingt-cinq (까뜨ㅎ브앙 생ㅋ)",
  "86": "quatre-vingt-six (까뜨ㅎ브앙 씨)",
  "87": "quatre-vingt-sept (까뜨ㅎ브앙 쎗)",
  "88": "quatre-vingt-huit (까뜨ㅎ브앙 위)",
  "89": "quatre-vingt-neuf (까뜨ㅎ브앙 느프)",
  "90": "quatre-vingt-dix (까뜨ㅎ브앙 디스)",
  
  "91": "quatre-vingt-onze (까뜨ㅎ브앙 옹즈)",
  "92": "quatre-vingt-douze (까뜨ㅎ브앙 두즈)",
  "93": "quatre-vingt-treize (까뜨ㅎ브앙 트ㅎ레즈)",
  "94": "quatre-vingt-quatorze (까뜨ㅎ브앙 카또ㅎ즈)",
  "95": "quatre-vingt-quinze (까뜨ㅎ브앙 캉즈)",
  "96": "quatre-vingt-seize (까뜨ㅎ브앙 세즈)",
  "97": "quatre-vingt-dix-sept (까뜨ㅎ브앙 디쎗)",
  "98": "quatre-vingt-dix-huit (까뜨ㅎ브앙 디쥐)",
  "99": "quatre-vingt-dix-neuf (까뜨ㅎ브앙 디즈느프)",
  "100": "cent (쌍)"

}

